package com.openminis.app.provider

import com.openminis.app.data.model.AgentContentPart
import com.openminis.app.data.model.LLMMessage
import com.openminis.app.data.model.LLMModel
import com.openminis.app.provider.openai.OpenAIProvider
import com.openminis.app.provider.openai.replayGeneratedImages
import kotlinx.coroutines.runBlocking
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test

class GeneratedImageHistoryTest {
    private val image = AgentContentPart.ImageData(byteArrayOf(1, 2, 3), "image/png")

    @Test
    fun `generated pixels reach the next request on both OpenAI protocols`() = runBlocking {
        for (responses in listOf(false, true)) MockWebServer().use { server ->
            server.start()
            val sse = if (responses) {
                "data: {\"type\":\"response.output_text.delta\",\"delta\":\"ok\"}\n\n" +
                    "data: {\"type\":\"response.completed\",\"response\":{\"status\":\"completed\"}}\n\n"
            } else "data: {\"choices\":[{\"delta\":{\"content\":\"ok\"},\"finish_reason\":\"stop\"}]}\n\ndata: [DONE]\n\n"
            server.enqueue(MockResponse().setHeader("Content-Type", "text/event-stream").setBody(sse))
            val provider = OpenAIProvider("fixture-key", LLMModel.gpt4o.copy(inputModalities = listOf("text", "image")),
                server.loopbackUrl("/v1").toString(), useResponsesAPI = responses)
            val history = listOf(
                LLMMessage(LLMMessage.Role.USER, "draw"),
                LLMMessage(LLMMessage.Role.ASSISTANT, "", contentParts = listOf(image)),
                LLMMessage(LLMMessage.Role.USER, "what color is it?"),
            )
            assertEquals("ok", provider.sendMessage(history, null, 1024).text)
            val body = JSONObject(server.takeRequest().body.readUtf8())
            val messages = body.getJSONArray(if (responses) "input" else "messages")
            val inputType = if (responses) "input_image" else "image_url"
            var images = 0
            for (i in 0 until messages.length()) {
                val message = messages.getJSONObject(i)
                val content = message.optJSONArray("content") ?: continue
                for (j in 0 until content.length()) if (content.getJSONObject(j).optString("type") == inputType) {
                    images++
                    assertEquals("user", message.getString("role"))
                    assertTrue(content.getJSONObject(j).toString().contains("data:image/png;base64,"))
                }
            }
            assertEquals(1, images)
            assertTrue(body.toString().contains("what color is it?"))
            assertTrue(body.toString().contains("generated by the assistant"))
            assertEquals(listOf(image), history[1].contentParts)
        }
    }

    @Test
    fun `tool result pairing remains intact when a turn also generated an image`() {
        val call = AgentContentPart.ToolUse("call-1", "fixture", JSONObject())
        val result = AgentContentPart.ToolResult("call-1", "fixture", "ok")
        val history = listOf(
            LLMMessage(LLMMessage.Role.ASSISTANT, "", contentParts = listOf(call, image)),
            LLMMessage(LLMMessage.Role.USER, "", contentParts = listOf(result)),
        )
        val replay = replayGeneratedImages(history)
        assertEquals(listOf(call), replay[0].contentParts)
        assertEquals(result, replay[1].contentParts.first())
        assertEquals(image, replay[1].contentParts.last())
        assertEquals(2, replay.size)
    }

    @Test
    fun `ordinary user images and text histories stay unchanged`() {
        val history = listOf(LLMMessage(LLMMessage.Role.USER, "", contentParts = listOf(image)))
        assertEquals(history, replayGeneratedImages(history))
        val assistant = LLMMessage(LLMMessage.Role.ASSISTANT, "plain text")
        assertEquals(listOf(assistant), replayGeneratedImages(listOf(assistant)))
    }
}
