#!/usr/bin/env python3
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BRANCH = "refactor/direct-ubuntu-runtime"


def run(*args: str, check: bool = True, cwd: Path | None = None, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(args), flush=True)
    merged = os.environ.copy()
    if env:
        merged.update(env)
    return subprocess.run(args, cwd=cwd or ROOT, env=merged, text=True, check=check)


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, content: str) -> None:
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(textwrap.dedent(content).lstrip("\n"), encoding="utf-8", newline="\n")


def replace_once(path: str, old: str, new: str) -> None:
    text = read(path)
    if text.count(old) != 1:
        raise SystemExit(f"expected exactly one match in {path}: {old[:120]!r}; got {text.count(old)}")
    write(path, text.replace(old, new, 1))


def replace_all(path: str, old: str, new: str, minimum: int = 1) -> None:
    text = read(path)
    count = text.count(old)
    if count < minimum:
        raise SystemExit(f"expected at least {minimum} matches in {path}: {old[:120]!r}; got {count}")
    write(path, text.replace(old, new))


def replace_between(path: str, start: str, end: str, replacement: str) -> None:
    text = read(path)
    a = text.find(start)
    b = text.find(end, a + len(start)) if a >= 0 else -1
    if a < 0 or b < 0:
        raise SystemExit(f"cannot locate replacement range in {path}: {start!r} .. {end!r}")
    write(path, text[:a] + textwrap.dedent(replacement).lstrip("\n") + text[b:])


def commit(message: str) -> None:
    run("git", "add", "-A")
    status = subprocess.run(["git", "diff", "--cached", "--quiet"], cwd=ROOT)
    if status.returncode == 0:
        print(f"no changes for commit: {message}")
        return
    run("git", "diff", "--cached", "--check")
    run("git", "commit", "-m", message)
    run("git", "push", "origin", f"HEAD:{BRANCH}")


def phase_payload_and_network_proxy() -> None:
    write(
        "src/native/root-network-proxy/Cargo.toml",
        r'''
        [package]
        name = "minis-root-network-proxy"
        version = "0.1.0"
        edition = "2021"
        license = "GPL-3.0-only"
        description = "Single-purpose root outbound proxy for Minis direct Ubuntu guests"
        publish = false

        [[bin]]
        name = "minis-root-network-proxy"
        path = "src/main.rs"

        [profile.release]
        lto = true
        codegen-units = 1
        panic = "abort"
        strip = true
        ''',
    )
    write(
        "src/native/root-network-proxy/Cargo.lock",
        r'''
        # This file is automatically @generated by Cargo.
        # It is not intended for manual editing.
        version = 3

        [[package]]
        name = "minis-root-network-proxy"
        version = "0.1.0"
        ''',
    )
    write(
        "src/native/root-network-proxy/src/main.rs",
        r'''
        use std::io::{BufReader, Read, Write};
        use std::net::{Ipv4Addr, SocketAddr, TcpListener, TcpStream, ToSocketAddrs, UdpSocket};
        use std::process::Command;
        use std::sync::atomic::{AtomicUsize, Ordering};
        use std::sync::Arc;
        use std::thread;
        use std::time::Duration;

        const DEFAULT_LISTEN: &str = "127.0.0.1:18787";
        const MAX_HEADER_BYTES: usize = 16 * 1024;
        const MAX_CONCURRENT: usize = 64;
        const FALLBACK_DNS: &[&str] = &[
            "223.5.5.5", "114.114.114.114", "119.29.29.29", "8.8.8.8", "1.1.1.1",
        ];

        #[cfg(target_os = "android")]
        unsafe extern "C" {
            fn prctl(option: i32, arg2: usize, arg3: usize, arg4: usize, arg5: usize) -> i32;
        }

        fn main() {
            #[cfg(target_os = "android")]
            unsafe {
                const PR_SET_PDEATHSIG: i32 = 1;
                const SIGTERM: usize = 15;
                let _ = prctl(PR_SET_PDEATHSIG, SIGTERM, 0, 0, 0);
            }

            let mut listen = DEFAULT_LISTEN.to_string();
            let mut args = std::env::args().skip(1);
            while let Some(arg) = args.next() {
                match arg.as_str() {
                    "--listen" => listen = args.next().unwrap_or_else(|| usage("missing --listen value")),
                    "--help" | "-h" => usage(""),
                    other => usage(&format!("unknown argument: {other}")),
                }
            }
            if listen != DEFAULT_LISTEN {
                usage("listen address is fixed to loopback 127.0.0.1:18787");
            }
            if let Err(error) = run_forever(&listen) {
                eprintln!("root-network-proxy: {error}");
                std::process::exit(1);
            }
        }

        fn usage(error: &str) -> ! {
            if !error.is_empty() {
                eprintln!("root-network-proxy: {error}");
            }
            eprintln!("usage: minis-root-network-proxy [--listen 127.0.0.1:18787]");
            std::process::exit(if error.is_empty() { 0 } else { 2 });
        }

        fn is_fake_ip(ip: Ipv4Addr) -> bool {
            let octets = ip.octets();
            octets[0] == 198 && (octets[1] == 18 || octets[1] == 19)
        }

        fn is_forbidden_target(ip: Ipv4Addr) -> bool {
            if is_fake_ip(ip) {
                return false;
            }
            ip.is_loopback() || ip.is_private() || ip.is_link_local() || ip.is_broadcast()
        }

        fn parse_target(first_line: &str) -> Result<(String, u16, bool, String), String> {
            let parts: Vec<&str> = first_line.split_whitespace().collect();
            if parts.len() < 2 {
                return Err("bad request line".into());
            }
            let method = parts[0].to_ascii_uppercase();
            let spec = parts[1];
            if method == "CONNECT" {
                let (host, port) = split_host_port(spec, 443)?;
                return Ok((host, port, true, first_line.to_string()));
            }
            if let Some(rest) = spec.strip_prefix("http://") {
                let (auth, path) = rest.split_once('/').unwrap_or((rest, ""));
                let (host, port) = split_host_port(auth, 80)?;
                let origin = format!(
                    "{method} /{path} {}",
                    parts.get(2).copied().unwrap_or("HTTP/1.1")
                );
                return Ok((host, port, false, origin));
            }
            Err("only CONNECT or absolute-form HTTP is supported".into())
        }

        fn split_host_port(spec: &str, default_port: u16) -> Result<(String, u16), String> {
            if let Some(rest) = spec.strip_prefix('[') {
                let (host, tail) = rest.split_once(']').ok_or("bad ipv6")?;
                let port = if let Some(port) = tail.strip_prefix(':') {
                    port.parse().map_err(|_| "bad port")?
                } else {
                    default_port
                };
                return Ok((host.to_string(), port));
            }
            if let Some((host, port)) = spec.rsplit_once(':') {
                if !port.is_empty() && port.chars().all(|c| c.is_ascii_digit()) {
                    return Ok((host.to_string(), port.parse().map_err(|_| "bad port")?));
                }
            }
            Ok((spec.to_string(), default_port))
        }

        fn run_forever(listen: &str) -> Result<(), String> {
            let server = TcpListener::bind(listen).map_err(|e| format!("bind {listen}: {e}"))?;
            let active = Arc::new(AtomicUsize::new(0));
            println!("READY {listen}");
            let _ = std::io::stdout().flush();
            for incoming in server.incoming() {
                let stream = match incoming {
                    Ok(stream) => stream,
                    Err(_) => continue,
                };
                if active.load(Ordering::SeqCst) >= MAX_CONCURRENT {
                    drop(stream);
                    continue;
                }
                active.fetch_add(1, Ordering::SeqCst);
                let active = Arc::clone(&active);
                thread::spawn(move || {
                    let _ = handle_client(stream);
                    active.fetch_sub(1, Ordering::SeqCst);
                });
            }
            Ok(())
        }

        fn handle_client(mut client: TcpStream) -> Result<(), String> {
            match handle_inner(&mut client) {
                Ok(()) => Ok(()),
                Err(error) => {
                    let body = error.as_bytes();
                    let _ = write!(
                        client,
                        "HTTP/1.1 502 Bad Gateway\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
                        body.len()
                    );
                    let _ = client.write_all(body);
                    Err(error)
                }
            }
        }

        fn handle_inner(client: &mut TcpStream) -> Result<(), String> {
            client.set_read_timeout(Some(Duration::from_secs(30))).ok();
            client.set_write_timeout(Some(Duration::from_secs(120))).ok();
            let mut reader = BufReader::new(client.try_clone().map_err(|e| e.to_string())?);
            let mut total = 0usize;
            let mut read_line_capped = |reader: &mut BufReader<TcpStream>| -> Result<String, String> {
                let mut line = String::new();
                let mut byte = [0u8; 1];
                loop {
                    match reader.read(&mut byte) {
                        Ok(0) => return Err("eof".into()),
                        Ok(_) => {
                            line.push(byte[0] as char);
                            if byte[0] == b'\n' {
                                break;
                            }
                            if total + line.len() > MAX_HEADER_BYTES {
                                return Err("header too large".into());
                            }
                        }
                        Err(error) => return Err(error.to_string()),
                    }
                }
                total += line.len();
                Ok(line)
            };

            let first = read_line_capped(&mut reader)?;
            let (host, port, is_connect, forward_line) = parse_target(first.trim_end())?;
            let mut head = Vec::new();
            if !is_connect {
                head.extend_from_slice(forward_line.as_bytes());
                head.extend_from_slice(b"\r\n");
            }
            loop {
                let line = read_line_capped(&mut reader)?;
                if !is_connect {
                    head.extend_from_slice(line.as_bytes());
                }
                if line == "\r\n" || line == "\n" || line.is_empty() {
                    break;
                }
            }
            let buffered = reader.buffer().to_vec();
            let mut peer = reader.into_inner();
            let ip = resolve_ipv4(&host)?;
            if is_forbidden_target(ip) {
                return Err(format!("blocked private/loopback target {host}({ip})"));
            }
            let mut upstream = TcpStream::connect(SocketAddr::from((ip, port)))
                .map_err(|e| format!("{host}({ip}):{port}: {e}"))?;
            if is_connect {
                peer.write_all(b"HTTP/1.1 200 Connection Established\r\n\r\n")
                    .map_err(|e| e.to_string())?;
                if !buffered.is_empty() {
                    upstream.write_all(&buffered).map_err(|e| e.to_string())?;
                }
            } else {
                upstream.write_all(&head).map_err(|e| e.to_string())?;
                if !buffered.is_empty() {
                    upstream.write_all(&buffered).map_err(|e| e.to_string())?;
                }
            }
            peer.set_read_timeout(None).ok();
            peer.set_write_timeout(None).ok();
            upstream.set_read_timeout(None).ok();
            upstream.set_write_timeout(None).ok();
            pump(peer, upstream)
        }

        fn resolve_ipv4(host: &str) -> Result<Ipv4Addr, String> {
            if let Ok(ip) = host.parse::<Ipv4Addr>() {
                return Ok(ip);
            }
            if let Ok(iter) = (host, 0).to_socket_addrs() {
                for addr in iter {
                    if let SocketAddr::V4(v4) = addr {
                        return Ok(*v4.ip());
                    }
                }
            }
            let mut last = String::new();
            for dns in discover_dns().into_iter().chain(FALLBACK_DNS.iter().map(|s| s.to_string())) {
                let Ok(server) = dns.parse::<Ipv4Addr>() else { continue };
                match dns_query_a(host, &format!("{server}:53")) {
                    Ok(ip) => return Ok(ip),
                    Err(error) => last = format!("{server}: {error}"),
                }
            }
            Err(format!("dns {host}: {last}"))
        }

        fn discover_dns() -> Vec<String> {
            let mut found = Vec::new();
            for key in [
                "net.dns1", "net.dns2", "net.dns3", "dhcp.wlan0.dns1", "dhcp.wlan0.dns2", "dhcp.eth0.dns1",
            ] {
                if let Ok(output) = Command::new("/system/bin/getprop").arg(key).output() {
                    let value = String::from_utf8_lossy(&output.stdout).trim().to_string();
                    if usable_dns(&value) && !found.contains(&value) {
                        found.push(value);
                    }
                }
            }
            if let Ok(output) = Command::new("/system/bin/dumpsys").arg("connectivity").output() {
                let text = String::from_utf8_lossy(&output.stdout);
                for line in text.lines() {
                    let lower = line.to_ascii_lowercase();
                    let Some(start) = lower.find("dnsaddresses") else { continue };
                    let rest = &line[start..];
                    let Some(open) = rest.find('[') else { continue };
                    let Some(close) = rest[open..].find(']') else { continue };
                    for token in rest[open + 1..open + close]
                        .split(|c: char| !c.is_ascii_hexdigit() && c != '.' && c != ':')
                    {
                        if usable_dns(token) && !found.iter().any(|value| value == token) {
                            found.push(token.to_string());
                        }
                    }
                }
            }
            found
        }

        fn usable_dns(value: &str) -> bool {
            if let Ok(ip) = value.parse::<Ipv4Addr>() {
                return !ip.is_unspecified() && !ip.is_loopback() && !ip.is_broadcast();
            }
            false
        }

        fn dns_query_a(host: &str, server: &str) -> Result<Ipv4Addr, String> {
            let mut query = Vec::new();
            query.extend_from_slice(&[0x12, 0x34, 0x01, 0x00, 0x00, 0x01, 0, 0, 0, 0, 0, 0]);
            for label in host.split('.') {
                if label.is_empty() || label.len() > 63 {
                    return Err("bad name".into());
                }
                query.push(label.len() as u8);
                query.extend_from_slice(label.as_bytes());
            }
            query.push(0);
            query.extend_from_slice(&[0, 1, 0, 1]);
            let socket = UdpSocket::bind("0.0.0.0:0").map_err(|e| e.to_string())?;
            socket.set_read_timeout(Some(Duration::from_secs(3))).map_err(|e| e.to_string())?;
            socket.send_to(&query, server).map_err(|e| e.to_string())?;
            let mut buf = [0u8; 512];
            let (size, _) = socket.recv_from(&mut buf).map_err(|e| e.to_string())?;
            parse_dns_a(&buf[..size])
        }

        fn parse_dns_a(msg: &[u8]) -> Result<Ipv4Addr, String> {
            if msg.len() < 12 {
                return Err("short dns".into());
            }
            let answers = u16::from_be_bytes([msg[6], msg[7]]) as usize;
            let mut index = 12usize;
            while index < msg.len() && msg[index] != 0 {
                index += 1 + msg[index] as usize;
            }
            index += 5;
            for _ in 0..answers {
                if index + 12 > msg.len() { break; }
                if msg[index] & 0xc0 == 0xc0 {
                    index += 2;
                } else {
                    while index < msg.len() && msg[index] != 0 {
                        index += 1 + msg[index] as usize;
                    }
                    index += 1;
                }
                if index + 10 > msg.len() { break; }
                let kind = u16::from_be_bytes([msg[index], msg[index + 1]]);
                let length = u16::from_be_bytes([msg[index + 8], msg[index + 9]]) as usize;
                index += 10;
                if kind == 1 && length == 4 && index + 4 <= msg.len() {
                    return Ok(Ipv4Addr::new(msg[index], msg[index + 1], msg[index + 2], msg[index + 3]));
                }
                index += length;
            }
            Err("no A".into())
        }

        fn pump(a: TcpStream, b: TcpStream) -> Result<(), String> {
            let a2 = a.try_clone().map_err(|e| e.to_string())?;
            let b2 = b.try_clone().map_err(|e| e.to_string())?;
            let handle = thread::spawn(move || copy(a2, b2));
            copy(b, a);
            let _ = handle.join();
            Ok(())
        }

        fn copy(mut reader: TcpStream, mut writer: TcpStream) {
            let mut buf = [0u8; 64 * 1024];
            loop {
                match reader.read(&mut buf) {
                    Ok(0) | Err(_) => break,
                    Ok(size) => {
                        if writer.write_all(&buf[..size]).is_err() {
                            break;
                        }
                    }
                }
            }
            let _ = writer.shutdown(std::net::Shutdown::Write);
        }

        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn connect_and_http_targets_parse() {
                let (host, port, connect, _) = parse_target("CONNECT example.com:443 HTTP/1.1").unwrap();
                assert_eq!((host, port, connect), ("example.com".to_string(), 443, true));
                let (host, port, connect, line) = parse_target("GET http://ports.ubuntu.com/ubuntu-ports/ HTTP/1.1").unwrap();
                assert_eq!((host, port, connect), ("ports.ubuntu.com".to_string(), 80, false));
                assert!(line.starts_with("GET /ubuntu-ports/ "));
            }

            #[test]
            fn lan_targets_are_blocked_but_fake_ip_is_allowed() {
                assert!(is_forbidden_target(Ipv4Addr::new(127, 0, 0, 1)));
                assert!(is_forbidden_target(Ipv4Addr::new(10, 0, 0, 1)));
                assert!(is_forbidden_target(Ipv4Addr::new(192, 168, 1, 1)));
                assert!(!is_forbidden_target(Ipv4Addr::new(198, 18, 0, 1)));
                assert!(!is_forbidden_target(Ipv4Addr::new(8, 8, 8, 8)));
            }
        }
        ''',
    )

    write(
        "scripts/build-root-network-proxy-android.sh",
        r'''
        #!/usr/bin/env bash
        set -euo pipefail

        ROOT="$(cd "$(dirname "$0")/.." && pwd)"
        DIST="${DIST:-$ROOT/dist}"
        TARGET="aarch64-linux-android"
        API_LEVEL="${ANDROID_MIN_SDK:-26}"
        NDK_VERSION="${MINIS_NDK_VERSION:-28.2.13676358}"

        case "$(uname -s)" in
          Linux) HOST_TAG="linux-x86_64"; TOOL_SUFFIX=""; CLANG_SUFFIX="" ;;
          Darwin) HOST_TAG="darwin-x86_64"; TOOL_SUFFIX=""; CLANG_SUFFIX="" ;;
          MINGW*|MSYS*) HOST_TAG="windows-x86_64"; TOOL_SUFFIX=".exe"; CLANG_SUFFIX=".cmd" ;;
          *) echo "error: unsupported host for root-network-proxy Android build" >&2; exit 2 ;;
        esac

        if [[ -n "${ANDROID_NDK_HOME:-}" ]]; then
          NDK="$ANDROID_NDK_HOME"
        elif [[ -n "${ANDROID_NDK_ROOT:-}" ]]; then
          NDK="$ANDROID_NDK_ROOT"
        elif [[ -n "${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}" ]]; then
          NDK="${ANDROID_SDK_ROOT:-${ANDROID_HOME}}/ndk/$NDK_VERSION"
        else
          echo "error: set ANDROID_SDK_ROOT or ANDROID_NDK_HOME" >&2
          exit 2
        fi
        if [[ "$HOST_TAG" == "windows-x86_64" ]]; then NDK="$(cygpath -u "$NDK")"; fi

        TOOLCHAIN="$NDK/toolchains/llvm/prebuilt/$HOST_TAG/bin"
        CLANG="$TOOLCHAIN/${TARGET}${API_LEVEL}-clang$CLANG_SUFFIX"
        READELF="$TOOLCHAIN/llvm-readelf$TOOL_SUFFIX"
        [[ -f "$CLANG" && -f "$READELF" ]] || { echo "error: Android NDK toolchain unavailable: $TOOLCHAIN" >&2; exit 2; }
        rustup target list --installed | grep -Fxq "$TARGET" || { echo "error: Rust target $TARGET is not installed" >&2; exit 2; }

        if [[ "$HOST_TAG" == "windows-x86_64" ]]; then
          export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$(cygpath -w "$CLANG")"
        else
          export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$CLANG"
        fi
        export RUSTFLAGS="${RUSTFLAGS:+$RUSTFLAGS }-C relocation-model=pic -C link-arg=-pie -C link-arg=-Wl,-z,max-page-size=16384 -C link-arg=-Wl,-z,common-page-size=16384"

        cargo build --locked --release --target "$TARGET" --manifest-path "$ROOT/src/native/root-network-proxy/Cargo.toml"
        BINARY="$ROOT/src/native/root-network-proxy/target/$TARGET/release/minis-root-network-proxy"
        [[ -f "$BINARY" ]] || { echo "error: root network proxy build output missing" >&2; exit 1; }

        HEADER="$($READELF -h -l -d -W "$BINARY")"
        grep -Eq 'Class:[[:space:]]+ELF64' <<<"$HEADER" || { echo "error: root network proxy is not ELF64" >&2; exit 1; }
        grep -Eq 'Machine:[[:space:]]+AArch64' <<<"$HEADER" || { echo "error: root network proxy is not AArch64" >&2; exit 1; }
        grep -Eq 'Type:[[:space:]]+DYN' <<<"$HEADER" || { echo "error: root network proxy is not PIE/ET_DYN" >&2; exit 1; }
        grep -Fq '/system/bin/linker64' <<<"$HEADER" || { echo "error: root network proxy is not linked for Android" >&2; exit 1; }
        if awk '$1 == "LOAD" && $NF != "0x4000" { bad=1 } END { exit bad ? 0 : 1 }' <<<"$HEADER"; then
          echo "error: root network proxy LOAD segments are not all 16 KB aligned" >&2
          exit 1
        fi
        grep -Fq 'libc.so' <<<"$HEADER" || { echo "error: root network proxy has no Android libc dependency" >&2; exit 1; }
        if grep -Eq 'ld-linux|libglibc' <<<"$HEADER"; then echo "error: root network proxy unexpectedly depends on glibc" >&2; exit 1; fi

        mkdir -p "$DIST"
        install -m 0755 "$BINARY" "$DIST/minis-root-network-proxy-arm64-v8a"
        sha256sum "$DIST/minis-root-network-proxy-arm64-v8a" > "$DIST/minis-root-network-proxy-arm64-v8a.sha256"
        echo "==> $DIST/minis-root-network-proxy-arm64-v8a"
        ''',
    )

    write(
        "scripts/verify-root-network-proxy.sh",
        r'''
        #!/usr/bin/env bash
        set -euo pipefail
        INPUT="${1:-}"
        [[ -n "$INPUT" && -e "$INPUT" ]] || { echo "usage: $0 path/to/dist-or.apk" >&2; exit 2; }

        python3 - "$INPUT" <<'PY'
        import hashlib
        import pathlib
        import re
        import sys
        import zipfile

        source = pathlib.Path(sys.argv[1])
        if source.is_dir():
            binary_path = source / "minis-root-network-proxy-arm64-v8a"
            checksum_path = source / "minis-root-network-proxy-arm64-v8a.sha256"
            if not binary_path.is_file() or not checksum_path.is_file():
                raise SystemExit("root network proxy payload is incomplete")
            binary = binary_path.read_bytes()
            expected = checksum_path.read_text(encoding="utf-8").split()[0].lower()
            if not re.fullmatch(r"[0-9a-f]{64}", expected):
                raise SystemExit("root network proxy checksum file is invalid")
            if hashlib.sha256(binary).hexdigest() != expected:
                raise SystemExit("root network proxy SHA-256 mismatch")
        else:
            with zipfile.ZipFile(source) as archive:
                path = "lib/arm64-v8a/libminisnetproxy.so"
                try:
                    binary = archive.read(path)
                except KeyError:
                    raise SystemExit(f"root network proxy is missing from APK: {path}") from None
                if "lib/arm64-v8a/libminisd.so" in archive.namelist():
                    raise SystemExit("obsolete libminisd.so is still packaged")

        if not binary.startswith(b"\x7fELF") or len(binary) < 20:
            raise SystemExit("root network proxy is not an ELF binary")
        if binary[4] != 2 or binary[5] != 1:
            raise SystemExit("root network proxy is not little-endian ELF64")
        if int.from_bytes(binary[16:18], "little") != 3:
            raise SystemExit("root network proxy is not PIE/ET_DYN")
        if int.from_bytes(binary[18:20], "little") != 183:
            raise SystemExit("root network proxy is not AArch64")
        print(f"root network proxy verified: sha256={hashlib.sha256(binary).hexdigest()}")
        PY
        ''',
    )

    write(
        "src/android/app/src/main/java/com/openminis/app/runtime/ubuntu/RootNetworkProxy.kt",
        r'''
        package com.openminis.app.runtime.ubuntu

        import android.content.Context
        import android.util.Log
        import kotlinx.coroutines.delay
        import kotlinx.coroutines.sync.Mutex
        import kotlinx.coroutines.sync.withLock
        import java.io.File
        import java.net.InetSocketAddress
        import java.net.Socket

        /**
         * Single-purpose Root outbound proxy for direct Ubuntu guests.
         *
         * Android/VPN BPF policy can block App-UID guest sockets while Root has
         * working egress. This loopback-only helper preserves that compatibility
         * without restoring a generic Root daemon, RPC protocol, or command API.
         */
        internal object RootNetworkProxy {
            const val PROXY_LISTEN = "127.0.0.1:18787"
            const val PROXY_URI = "http://127.0.0.1:18787"
            private const val TAG = "RootNetworkProxy"
            private const val BINARY = "libminisnetproxy.so"
            private val lock = Mutex()

            data class Status(val ready: Boolean, val detail: String? = null)

            @Volatile
            private var process: Process? = null

            suspend fun ensureReady(context: Context): Status = lock.withLock {
                if (listenerReady()) return@withLock Status(true)
                process?.let { stale ->
                    runCatching { stale.destroyForcibly() }
                    process = null
                }

                val su = DirectRootRunner.findSu()
                    ?: return@withLock Status(false, "Root launcher is unavailable for outbound network proxy")
                val binary = File(context.applicationInfo.nativeLibraryDir, BINARY)
                if (!binary.isFile) {
                    return@withLock Status(false, "packaged Root network proxy is missing: ${binary.absolutePath}")
                }

                val command = "exec ${DirectRootRunner.shellQuote(binary.absolutePath)} --listen ${DirectRootRunner.shellQuote(PROXY_LISTEN)}"
                val child = try {
                    ProcessBuilder(su, "-c", command)
                        .redirectErrorStream(true)
                        .start()
                } catch (error: Throwable) {
                    return@withLock Status(false, "cannot start Root network proxy: ${error.message}")
                }
                process = child
                Thread({
                    runCatching {
                        child.inputStream.bufferedReader().useLines { lines ->
                            lines.forEach { Log.d(TAG, it) }
                        }
                    }
                }, "minis-root-network-proxy-log").apply {
                    isDaemon = true
                    start()
                }

                repeat(80) {
                    if (!child.isAlive) {
                        process = null
                        return@withLock Status(false, "Root network proxy exited before becoming ready")
                    }
                    if (listenerReady()) return@withLock Status(true)
                    delay(25)
                }
                runCatching { child.destroyForcibly() }
                process = null
                Status(false, "Root network proxy did not bind $PROXY_LISTEN")
            }

            fun proxyEnv(): Map<String, String> = linkedMapOf(
                "http_proxy" to PROXY_URI,
                "https_proxy" to PROXY_URI,
                "HTTP_PROXY" to PROXY_URI,
                "HTTPS_PROXY" to PROXY_URI,
                "all_proxy" to PROXY_URI,
                "ALL_PROXY" to PROXY_URI,
                "no_proxy" to "localhost,127.0.0.1,::1",
                "NO_PROXY" to "localhost,127.0.0.1,::1",
            )

            private fun listenerReady(): Boolean = try {
                Socket().use { socket ->
                    socket.connect(InetSocketAddress("127.0.0.1", 18787), 150)
                }
                true
            } catch (_: Throwable) {
                false
            }
        }
        ''',
    )

    kernel = read("src/android/app/src/main/java/com/openminis/app/runtime/ubuntu/UbuntuKernel.kt")
    marker = '''        val provisioned = UbuntuProvisioner.ensureProvisioned(ctx)\n'''
    if marker not in kernel:
        raise SystemExit("UbuntuKernel provisioning marker changed")
    network = '''        val network = RootNetworkProxy.ensureReady(ctx)\n        if (!network.ready) {\n            return@withLock Status(false, error = network.detail ?: "Root outbound network proxy unavailable")\n        }\n\n'''
    kernel = kernel.replace(marker, network + marker, 1)
    kernel = kernel.replace("env.putAll(RuntimePathRegistry.systemProxyEnv(ctx))", "env.putAll(RootNetworkProxy.proxyEnv())", 1)
    write("src/android/app/src/main/java/com/openminis/app/runtime/ubuntu/UbuntuKernel.kt", kernel)

    provisioner = read("src/android/app/src/main/java/com/openminis/app/runtime/ubuntu/UbuntuProvisioner.kt")
    provisioner = provisioner.replace("import com.openminis.app.runtime.RuntimePathRegistry\n", "")
    provisioner = provisioner.replace(
        '        val proxy = RuntimePathRegistry.systemProxyEnv(context)["http_proxy"].orEmpty()\n',
        '        val proxy = RootNetworkProxy.PROXY_URI\n',
        1,
    )
    write("src/android/app/src/main/java/com/openminis/app/runtime/ubuntu/UbuntuProvisioner.kt", provisioner)

    runtime_paths = read("src/android/app/src/main/java/com/openminis/app/runtime/RuntimePathRegistry.kt")
    runtime_paths = runtime_paths.replace(
        " * Ubuntu process and mount-namespace lifecycle is owned by minisd; this object\n * only maintains the app-visible path registry, SAF mount snapshots, and host\n * environment helpers consumed while constructing runtime requests.\n",
        " * Ubuntu process and mount-namespace lifecycle is App-owned by the direct runtime;\n * this object maintains the app-visible path registry, SAF mount snapshots, and\n * host environment helpers consumed while constructing direct launches.\n",
        1,
    )
    runtime_paths = runtime_paths.replace("External mounts are broker-owned", "External mounts are direct-runtime-owned")
    runtime_paths = runtime_paths.replace("applyMountedFoldersSnapshot: broker-owned mounts", "applyMountedFoldersSnapshot: direct-runtime-owned mounts")
    runtime_paths = runtime_paths.replace("External roots are indexed through broker listings", "External roots are indexed through direct runtime listings")
    write("src/android/app/src/main/java/com/openminis/app/runtime/RuntimePathRegistry.kt", runtime_paths)

    build_gradle = read("src/android/app/build.gradle.kts")
    build_gradle = build_gradle.replace(
        '''val packagedRuntimeManifest = runtimeDistDir.resolve("runtime-manifest.json")\nval packagedMinisdAndroid = runtimeDistDir.resolve("minisd-arm64-v8a")\nval generatedRuntimeAssets = layout.buildDirectory.dir("generated/runtimePayload/assets")\nval generatedRuntimeJniLibs = layout.buildDirectory.dir("generated/runtimePayload/jniLibs")\n''',
        '''val packagedRuntimeManifest = runtimeDistDir.resolve("runtime-manifest.json")\nval packagedRootNetworkProxy = runtimeDistDir.resolve("minis-root-network-proxy-arm64-v8a")\nval packagedRootNetworkProxySha = runtimeDistDir.resolve("minis-root-network-proxy-arm64-v8a.sha256")\nval generatedRuntimeAssets = layout.buildDirectory.dir("generated/runtimePayload/assets")\nval generatedRootNetworkProxyJniLibs = layout.buildDirectory.dir("generated/rootNetworkProxy/jniLibs")\n''',
        1,
    )
    build_gradle = build_gradle.replace(
        '''    sourceSets.getByName("main") {\n        assets.srcDir(generatedRuntimeAssets)\n        jniLibs.srcDir(generatedRuntimeJniLibs)\n    }\n\n    packaging {\n        jniLibs {\n            // minisd is executed from ApplicationInfo.nativeLibraryDir. Force\n            // Package Manager to materialize the APK-owned ELF on disk.\n            useLegacyPackaging = true\n            keepDebugSymbols += "**/libminisd.so"\n        }\n    }\n''',
        '''    sourceSets.getByName("main") {\n        assets.srcDir(generatedRuntimeAssets)\n        jniLibs.srcDir(generatedRootNetworkProxyJniLibs)\n    }\n\n    packaging {\n        jniLibs {\n            // The single-purpose Root network proxy executes directly from\n            // ApplicationInfo.nativeLibraryDir, so the ELF must be materialized.\n            useLegacyPackaging = true\n        }\n    }\n''',
        1,
    )
    start = build_gradle.index("val stageRuntimePayload by tasks.registering {")
    end = build_gradle.index('tasks.matching { it.name.startsWith("merge") && it.name.endsWith("Assets") }', start)
    new_tasks = r'''val stageRuntimePayload by tasks.registering {
    group = "build"
    description = "Stages an optional verified rootfs-only runtime payload from dist into Android assets."
    inputs.files(packagedRootfs, packagedRuntimeManifest)
    outputs.dir(generatedRuntimeAssets)
    outputs.upToDateWhen { false }
    doLast {
        val inputs = listOf(packagedRootfs, packagedRuntimeManifest)
        val missing = inputs.filterNot { it.isFile }
        val required = System.getenv("MINIS_REQUIRE_RUNTIME_PAYLOAD") == "1"
        if ((missing.isNotEmpty() && missing.size != inputs.size) || (required && missing.isNotEmpty())) {
            throw GradleException("Rootfs runtime payload is incomplete; missing: ${missing.joinToString { it.path }}")
        }

        delete(generatedRuntimeAssets)
        if (missing.isNotEmpty()) return@doLast

        val manifest = JsonSlurper().parse(packagedRuntimeManifest) as? Map<*, *>
            ?: throw GradleException("Runtime manifest is not a JSON object")
        val expected = mapOf(
            "schemaVersion" to 3,
            "distro" to "ubuntu",
            "arch" to "arm64",
            "profile" to "base",
        )
        expected.forEach { (key, value) ->
            if (manifest[key] != value) throw GradleException("Runtime manifest $key must be $value")
        }
        if (manifest.keys.any { it in setOf("minisdVersion", "minisdSha256", "protocolVersion") }) {
            throw GradleException("Runtime manifest contains obsolete broker fields")
        }
        if (manifest["rootfsSha256"] != sha256(packagedRootfs)) {
            throw GradleException("Runtime manifest rootfs SHA-256 mismatch")
        }
        if (manifest["requiredCommands"] != listOf("python3", "git", "curl")) {
            throw GradleException("Runtime manifest requiredCommands mismatch")
        }

        copy {
            from(packagedRootfs) { rename { "ubuntu-arm64-rootfs.tar.gz.aapt-preserve" } }
            from(packagedRuntimeManifest)
            into(generatedRuntimeAssets.get().dir("minis-runtime"))
        }
    }
}

val stageRootNetworkProxy by tasks.registering {
    group = "build"
    description = "Stages the single-purpose Root outbound proxy separately from the rootfs payload."
    inputs.files(packagedRootNetworkProxy, packagedRootNetworkProxySha)
    outputs.dir(generatedRootNetworkProxyJniLibs)
    outputs.upToDateWhen { false }
    doLast {
        val inputs = listOf(packagedRootNetworkProxy, packagedRootNetworkProxySha)
        val missing = inputs.filterNot { it.isFile }
        val required = System.getenv("MINIS_REQUIRE_RUNTIME_PAYLOAD") == "1"
        val runtimePresent = packagedRootfs.isFile || packagedRuntimeManifest.isFile
        if ((missing.isNotEmpty() && missing.size != inputs.size) || ((required || runtimePresent) && missing.isNotEmpty())) {
            throw GradleException("Root network proxy payload is incomplete; missing: ${missing.joinToString { it.path }}")
        }

        delete(generatedRootNetworkProxyJniLibs)
        if (missing.isNotEmpty()) return@doLast
        val expected = packagedRootNetworkProxySha.readText().trim().split(Regex("\\s+"), limit = 2).firstOrNull().orEmpty().lowercase()
        if (!expected.matches(Regex("[0-9a-f]{64}")) || expected != sha256(packagedRootNetworkProxy)) {
            throw GradleException("Root network proxy SHA-256 mismatch")
        }
        copy {
            from(packagedRootNetworkProxy)
            into(generatedRootNetworkProxyJniLibs.get().dir("arm64-v8a"))
            rename { "libminisnetproxy.so" }
        }
    }
}

'''
    build_gradle = build_gradle[:start] + new_tasks + build_gradle[end:]
    build_gradle = build_gradle.replace(
        'tasks.matching { it.name.startsWith("merge") && it.name.endsWith("JniLibFolders") }\n    .configureEach { dependsOn(stageRuntimePayload) }',
        'tasks.matching { it.name.startsWith("merge") && it.name.endsWith("JniLibFolders") }\n    .configureEach { dependsOn(stageRootNetworkProxy) }',
        1,
    )
    build_gradle = build_gradle.replace(
        '    dependsOn(stageRuntimePayload)\n    dependsOn(verifyRcloneAar16k)',
        '    dependsOn(stageRuntimePayload)\n    dependsOn(stageRootNetworkProxy)\n    dependsOn(verifyRcloneAar16k)',
        1,
    )
    write("src/android/app/build.gradle.kts", build_gradle)

    write(
        "scripts/build-runtime-payload.sh",
        r'''
        #!/usr/bin/env bash
        set -euo pipefail
        ROOT="$(cd "$(dirname "$0")/.." && pwd)"
        DIST="${DIST:-$ROOT/dist}"
        export DIST

        bash "$ROOT/scripts/build-ubuntu-rootfs.sh"

        python3 - "$DIST" <<'PY'
        import hashlib
        import json
        import pathlib
        import re
        import sys

        dist = pathlib.Path(sys.argv[1])
        rootfs = dist / "ubuntu-arm64-rootfs.tar.gz"
        rootfs_meta_path = dist / "ubuntu-arm64-rootfs.manifest.json"

        def sha256(path):
            digest = hashlib.sha256()
            with path.open("rb") as stream:
                for chunk in iter(lambda: stream.read(1024 * 1024), b""):
                    digest.update(chunk)
            return digest.hexdigest()

        meta = json.loads(rootfs_meta_path.read_text(encoding="utf-8"))
        rootfs_sha = sha256(rootfs)
        if meta.get("sha256") != rootfs_sha:
            raise SystemExit("rootfs build manifest SHA-256 does not match archive")
        version = meta.get("version", "")
        if not re.fullmatch(r"ubuntu-24\.04-r[1-9][0-9]*-[0-9a-f]{16}", version):
            raise SystemExit(f"invalid rootfs version: {version}")
        if not version.endswith(rootfs_sha[:16]):
            raise SystemExit("rootfs version is not derived from final archive")

        manifest = {
            "schemaVersion": 3,
            "distro": "ubuntu",
            "release": meta["release"],
            "arch": "arm64",
            "profile": meta["profile"],
            "revision": meta["rootfsRevision"],
            "rootfsVersion": version,
            "rootfsSha256": rootfs_sha,
            "upstreamSha256": meta["upstream_sha256"],
            "provisionRevision": meta["provisionRevision"],
            "requiredCommands": meta["requiredCommands"],
        }
        (dist / "runtime-manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        PY

        bash "$ROOT/scripts/verify-runtime-payload.sh" "$DIST"
        ''',
    )

    write(
        "scripts/verify-runtime-payload.sh",
        r'''
        #!/usr/bin/env bash
        set -euo pipefail
        INPUT="${1:-}"
        [[ -n "$INPUT" && -e "$INPUT" ]] || { echo "usage: $0 path/to/dist-or.apk" >&2; exit 2; }

        python3 - "$INPUT" <<'PY'
        import hashlib
        import io
        import json
        import pathlib
        import re
        import sys
        import tarfile
        import zipfile

        source = pathlib.Path(sys.argv[1])
        if source.is_dir():
            rootfs_path = source / "ubuntu-arm64-rootfs.tar.gz"
            manifest_path = source / "runtime-manifest.json"
            if not rootfs_path.is_file() or not manifest_path.is_file():
                raise SystemExit("rootfs runtime payload is incomplete")
            if (source / "minisd-arm64-v8a").exists():
                raise SystemExit("obsolete minisd payload is still present")
            rootfs = rootfs_path.read_bytes()
            manifest_raw = manifest_path.read_bytes()
        else:
            with zipfile.ZipFile(source) as archive:
                names = set(archive.namelist())
                if "lib/arm64-v8a/libminisd.so" in names:
                    raise SystemExit("obsolete libminisd.so is still packaged")
                try:
                    rootfs = archive.read("assets/minis-runtime/ubuntu-arm64-rootfs.tar.gz")
                    manifest_raw = archive.read("assets/minis-runtime/runtime-manifest.json")
                except KeyError as error:
                    raise SystemExit(f"rootfs runtime payload is missing: {error.args[0]}") from None

        if not rootfs.startswith(b"\x1f\x8b"):
            raise SystemExit("packaged rootfs is not gzip data")

        required_rootfs = {
            "etc/os-release", "etc/passwd", "etc/group", "etc/minis/rootfs.json",
            "workspace", "memory", "skills", "shared", "proc", "sys", "dev", "tmp", "run", "var/minis",
        }
        required_real_directories = {
            "etc", "etc/minis", "workspace", "memory", "skills", "shared", "proc", "sys", "dev", "tmp", "run", "var", "var/minis",
        }
        optional_real_directories = {"dev/pts", "dev/shm", "mnt", "home", "home/minis", "root"}
        required_regular_files = {"etc/passwd", "etc/group", "etc/minis/rootfs.json"}
        allowed_absolute_links = {
            "etc/alternatives/awk": "/usr/bin/mawk",
            "etc/alternatives/nawk": "/usr/bin/mawk",
            "etc/alternatives/pager": "/bin/more",
            "etc/alternatives/rmt": "/usr/sbin/rmt-tar",
            "etc/alternatives/which": "/usr/bin/which.debianutils",
            "etc/rmt": "/usr/sbin/rmt",
            "usr/bin/awk": "/etc/alternatives/awk",
            "usr/bin/nawk": "/etc/alternatives/nawk",
            "usr/bin/pager": "/etc/alternatives/pager",
            "usr/bin/which": "/etc/alternatives/which",
            "usr/sbin/rmt": "/etc/alternatives/rmt",
            "etc/systemd/system/multi-user.target.wants/e2scrub_reap.service": "/lib/systemd/system/e2scrub_reap.service",
            "etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer": "/lib/systemd/system/apt-daily-upgrade.timer",
            "etc/systemd/system/timers.target.wants/apt-daily.timer": "/lib/systemd/system/apt-daily.timer",
            "etc/systemd/system/timers.target.wants/dpkg-db-backup.timer": "/lib/systemd/system/dpkg-db-backup.timer",
            "etc/systemd/system/timers.target.wants/e2scrub_all.timer": "/lib/systemd/system/e2scrub_all.timer",
            "etc/systemd/system/timers.target.wants/fstrim.timer": "/lib/systemd/system/fstrim.timer",
            "etc/systemd/system/timers.target.wants/motd-news.timer": "/lib/systemd/system/motd-news.timer",
            "var/run": "/run", "var/lock": "/run/lock",
            "var/minis/workspace": "/workspace", "var/minis/attachments": "/workspace/attachments",
            "var/minis/offloads": "/workspace/offloads", "var/minis/browser": "/workspace/browser",
            "var/minis/memory": "/memory", "var/minis/skills": "/skills", "var/minis/shared": "/shared",
        }

        def normalize_path(raw):
            value = raw.strip()
            while value.startswith("./"):
                value = value[2:]
            value = value.rstrip("/")
            if not value or value == ".":
                return None
            parts = value.split("/")
            if value.startswith("/") or any(not part or part in {".", ".."} or any(ord(c) < 32 for c in part) for part in parts):
                raise SystemExit(f"packaged rootfs contains an unsafe path: {raw!r}")
            return "/".join(parts)

        def normalize_link(entry, target):
            if not target or "\x00" in target:
                raise SystemExit(f"packaged rootfs contains an unsafe link: {entry} -> {target}")
            if target.startswith("/"):
                if allowed_absolute_links.get(entry) != target:
                    raise SystemExit(f"packaged rootfs contains an unsafe link: {entry} -> {target}")
                return target
            parts = entry.split("/")[:-1]
            for component in target.split("/"):
                if not component or component == ".":
                    continue
                if any(ord(c) < 32 for c in component):
                    raise SystemExit(f"packaged rootfs contains an unsafe link: {entry} -> {target}")
                if component == "..":
                    if not parts:
                        raise SystemExit(f"packaged rootfs contains an unsafe link: {entry} -> {target}")
                    parts.pop()
                else:
                    parts.append(component)
            if not parts:
                raise SystemExit(f"packaged rootfs contains an unsafe link: {entry} -> {target}")
            return "/".join(parts)

        def reject_link_escape(path, symlinks):
            if not path:
                return
            components = path.split("/")
            visited = set()
            while True:
                replaced = False
                for index in range(1, len(components) + 1):
                    prefix = "/".join(components[:index])
                    target = symlinks.get(prefix)
                    if target is None:
                        continue
                    if target.startswith("/"):
                        raise SystemExit(f"packaged rootfs path resolves through an absolute link: {path}")
                    if prefix in visited:
                        raise SystemExit(f"packaged rootfs path contains a symlink cycle: {path}")
                    visited.add(prefix)
                    components = target.split("/") + components[index:]
                    replaced = True
                    break
                if not replaced:
                    return

        try:
            with tarfile.open(fileobj=io.BytesIO(rootfs), mode="r:gz") as tar:
                members = {}
                regular_names = set()
                hard_links = []
                symlink_targets = {}
                expanded_bytes = 0
                for member in tar.getmembers():
                    name = normalize_path(member.name)
                    if name is None:
                        if not member.isdir():
                            raise SystemExit("packaged rootfs has a non-directory root entry")
                        continue
                    if name in members:
                        raise SystemExit(f"packaged rootfs contains duplicate entry: {name}")
                    if member.isdir(): kind = "dir"
                    elif member.isfile():
                        kind = "file"
                        regular_names.add(name)
                        expanded_bytes += member.size
                        if expanded_bytes > 2 * 1024 * 1024 * 1024:
                            raise SystemExit("packaged rootfs expands beyond 2 GiB")
                    elif member.issym():
                        kind = "symlink"
                        symlink_targets[name] = normalize_link(name, member.linkname)
                    elif member.islnk():
                        kind = "hardlink"
                        hard_links.append((name, normalize_path(member.linkname)))
                    else:
                        raise SystemExit(f"packaged rootfs contains unsupported node: {name}")
                    if name in required_real_directories and kind != "dir":
                        raise SystemExit(f"packaged rootfs layout entry is not a real directory: {name}")
                    if name in optional_real_directories and kind != "dir":
                        raise SystemExit(f"packaged rootfs optional directory is not real: {name}")
                    if name in required_regular_files and kind != "file":
                        raise SystemExit(f"packaged rootfs required file is not regular: {name}")
                    members[name] = member
                for name in members:
                    reject_link_escape(name.rsplit("/", 1)[0] if "/" in name else "", symlink_targets)
                for target in symlink_targets.values():
                    if not target.startswith("/"):
                        reject_link_escape(target, symlink_targets)
                for name, target in hard_links:
                    if target is None or target not in regular_names:
                        raise SystemExit(f"packaged rootfs hardlink target is not a regular file: {name} -> {target}")
                missing = sorted(required_rootfs - members.keys())
                if missing:
                    raise SystemExit(f"packaged rootfs is missing layout entries: {', '.join(missing)}")
                if "bin/bash" not in members and "usr/bin/bash" not in members and "bin/sh" not in members:
                    raise SystemExit("packaged rootfs has no shell")
                metadata_file = tar.extractfile(members["etc/minis/rootfs.json"])
                if metadata_file is None:
                    raise SystemExit("packaged rootfs metadata is not a regular file")
                rootfs_metadata = json.load(metadata_file)
        except (tarfile.TarError, json.JSONDecodeError) as error:
            raise SystemExit(f"packaged rootfs archive is invalid: {error}") from None

        try:
            manifest = json.loads(manifest_raw.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as error:
            raise SystemExit(f"runtime manifest is invalid JSON: {error}") from None
        if not isinstance(manifest, dict):
            raise SystemExit("runtime manifest is not an object")
        forbidden = {"minisdVersion", "minisdSha256", "protocolVersion"}
        present = sorted(forbidden & manifest.keys())
        if present:
            raise SystemExit(f"runtime manifest contains obsolete broker fields: {', '.join(present)}")

        rootfs_sha = hashlib.sha256(rootfs).hexdigest()
        required = {"schemaVersion": 3, "distro": "ubuntu", "arch": "arm64", "profile": "base"}
        for key, expected in required.items():
            if manifest.get(key) != expected:
                raise SystemExit(f"runtime manifest {key} must be {expected!r}")
        if manifest.get("rootfsSha256") != rootfs_sha:
            raise SystemExit("runtime manifest rootfs SHA-256 mismatch")
        pinned = "7b2dced6dd56ad5e4a813fa25c8de307b655fdabc6ea9213175a92c48dabb048"
        if manifest.get("upstreamSha256") != pinned or rootfs_metadata.get("upstream_sha256") != pinned:
            raise SystemExit("runtime payload does not use pinned Ubuntu upstream SHA-256")
        if (
            rootfs_metadata.get("distro") != "ubuntu"
            or not str(rootfs_metadata.get("version", "")).startswith("24.04")
            or rootfs_metadata.get("arch") != "arm64"
            or rootfs_metadata.get("profile") != "base"
            or not isinstance(rootfs_metadata.get("revision"), int)
            or isinstance(rootfs_metadata.get("revision"), bool)
            or rootfs_metadata["revision"] <= 0
        ):
            raise SystemExit("packaged rootfs metadata has unsupported identity")
        if manifest.get("release") != rootfs_metadata.get("release") or not str(manifest.get("release", "")).startswith("24.04"):
            raise SystemExit("runtime manifest release does not match Ubuntu 24.04 metadata")
        if manifest.get("revision") != rootfs_metadata.get("revision"):
            raise SystemExit("runtime manifest revision does not match rootfs metadata")
        version = manifest.get("rootfsVersion", "")
        if not re.fullmatch(r"ubuntu-24\.04-r[1-9][0-9]*-[0-9a-f]{16}", version):
            raise SystemExit("runtime manifest has invalid rootfsVersion")
        if not version.endswith(rootfs_sha[:16]):
            raise SystemExit("runtime rootfsVersion does not match rootfs digest")
        revision = int(version.split("-r", 1)[1].split("-", 1)[0])
        if revision != manifest.get("revision"):
            raise SystemExit("runtime rootfsVersion revision does not match manifest")
        if not isinstance(manifest.get("provisionRevision"), int) or isinstance(manifest.get("provisionRevision"), bool) or manifest["provisionRevision"] <= 0:
            raise SystemExit("runtime manifest provisionRevision must be positive")
        if manifest.get("requiredCommands") != ["python3", "git", "curl"]:
            raise SystemExit("runtime manifest requiredCommands mismatch")

        print(f"rootfs runtime payload verified: rootfs={rootfs_sha}")
        PY
        ''',
    )

    write(
        "scripts/test-runtime-payload-verification.sh",
        r'''
        #!/usr/bin/env bash
        set -euo pipefail
        ROOT="$(cd "$(dirname "$0")/.." && pwd)"
        VERIFY="$ROOT/scripts/verify-runtime-payload.sh"
        TMP="$(mktemp -d)"
        trap 'rm -rf "$TMP"' EXIT

        make_fixture() {
          local dir="$1"
          mkdir -p "$dir"
          python3 - "$dir" <<'PY'
        import hashlib, io, json, pathlib, sys, tarfile
        root = pathlib.Path(sys.argv[1])
        metadata = {
            "distro": "ubuntu", "version": "24.04", "release": "24.04.3", "arch": "arm64",
            "profile": "base", "revision": 1,
            "upstream_sha256": "7b2dced6dd56ad5e4a813fa25c8de307b655fdabc6ea9213175a92c48dabb048",
        }
        with tarfile.open(root / "ubuntu-arm64-rootfs.tar.gz", "w:gz") as tar:
            for name in ("etc", "etc/minis", "workspace", "memory", "skills", "shared", "proc", "sys", "dev", "tmp", "run", "var", "var/minis"):
                info = tarfile.TarInfo(name); info.type = tarfile.DIRTYPE; tar.addfile(info)
            for name, content in {
                "etc/os-release": b'VERSION_ID="24.04"\n', "etc/passwd": b"root:x:0:0:root:/root:/bin/bash\n",
                "etc/group": b"root:x:0:\n", "etc/minis/rootfs.json": json.dumps(metadata).encode(), "bin/bash": b"#!/bin/sh\n",
            }.items():
                info = tarfile.TarInfo(name); info.size = len(content); info.mode = 0o755 if name == "bin/bash" else 0o644
                tar.addfile(info, io.BytesIO(content))
        rootfs = (root / "ubuntu-arm64-rootfs.tar.gz").read_bytes()
        digest = hashlib.sha256(rootfs).hexdigest()
        manifest = {
            "schemaVersion": 3, "distro": "ubuntu", "release": "24.04.3", "arch": "arm64", "profile": "base",
            "revision": 1, "rootfsVersion": f"ubuntu-24.04-r1-{digest[:16]}", "rootfsSha256": digest,
            "upstreamSha256": "7b2dced6dd56ad5e4a813fa25c8de307b655fdabc6ea9213175a92c48dabb048",
            "provisionRevision": 1, "requiredCommands": ["python3", "git", "curl"],
        }
        (root / "runtime-manifest.json").write_text(json.dumps(manifest), encoding="utf-8")
        PY
        }

        mutate_tar() {
          local dir="$1" mode="$2"
          python3 - "$dir" "$mode" <<'PY'
        import io, json, pathlib, sys, tarfile
        root = pathlib.Path(sys.argv[1]); mode = sys.argv[2]
        src = root / "ubuntu-arm64-rootfs.tar.gz"
        members = []
        with tarfile.open(src, "r:gz") as tar:
            for member in tar.getmembers():
                data = tar.extractfile(member).read() if member.isfile() else None
                members.append((member, data))
        with tarfile.open(src, "w:gz") as tar:
            for member, data in members:
                if mode == "malformed_metadata" and member.name == "etc/minis/rootfs.json": data = b"{}"
                if mode == "unsafe_symlink" and member.name == "workspace":
                    member = tarfile.TarInfo("workspace"); member.type = tarfile.SYMTYPE; member.linkname = "../../data"
                    data = None
                tar.addfile(member, io.BytesIO(data) if data is not None else None)
            if mode == "duplicate_entry":
                dup = tarfile.TarInfo("workspace"); dup.type = tarfile.DIRTYPE; tar.addfile(dup)
        PY
        }

        expect_failure() {
          local name="$1"; shift
          local dir="$TMP/$name"
          make_fixture "$dir"
          "$@" "$dir"
          if "$VERIFY" "$dir" >"$TMP/$name.log" 2>&1; then
            echo "FAIL: $name unexpectedly succeeded" >&2; exit 1
          fi
          echo "PASS: $name"
        }

        make_fixture "$TMP/valid"
        "$VERIFY" "$TMP/valid"
        expect_failure tampered_rootfs sh -c 'printf tampered >> "$1/ubuntu-arm64-rootfs.tar.gz"' _
        expect_failure missing_rootfs sh -c 'rm "$1/ubuntu-arm64-rootfs.tar.gz"' _
        expect_failure malformed_metadata sh -c '"$2" "$1" malformed_metadata' _ "$0"
        expect_failure wrong_upstream_sha sh -c 'python3 - "$1/runtime-manifest.json" <<"PY"\nimport json, pathlib, sys\np=pathlib.Path(sys.argv[1]); d=json.loads(p.read_text()); d["upstreamSha256"]="0"*64; p.write_text(json.dumps(d))\nPY' _
        expect_failure wrong_arch sh -c 'python3 - "$1/runtime-manifest.json" <<"PY"\nimport json, pathlib, sys\np=pathlib.Path(sys.argv[1]); d=json.loads(p.read_text()); d["arch"]="x86_64"; p.write_text(json.dumps(d))\nPY' _
        expect_failure invalid_revision sh -c 'python3 - "$1/runtime-manifest.json" <<"PY"\nimport json, pathlib, sys\np=pathlib.Path(sys.argv[1]); d=json.loads(p.read_text()); d["revision"]=0; p.write_text(json.dumps(d))\nPY' _
        expect_failure obsolete_broker_field sh -c 'python3 - "$1/runtime-manifest.json" <<"PY"\nimport json, pathlib, sys\np=pathlib.Path(sys.argv[1]); d=json.loads(p.read_text()); d["minisdSha256"]="0"*64; p.write_text(json.dumps(d))\nPY' _

        # Tar structural failures use direct fixture mutations.
        for mode in unsafe_symlink duplicate_entry malformed_metadata; do
          dir="$TMP/$mode"; make_fixture "$dir"; mutate_tar "$dir" "$mode"
          if "$VERIFY" "$dir" >"$TMP/$mode.log" 2>&1; then echo "FAIL: $mode unexpectedly succeeded" >&2; exit 1; fi
          echo "PASS: $mode"
        done
        echo "All rootfs-only runtime payload verification tests passed."
        ''',
    )

    # Fix the generated test script's accidental helper invocation line by keeping only direct tar loop.
    test_payload = read("scripts/test-runtime-payload-verification.sh")
    bad = 'expect_failure malformed_metadata sh -c \'"$2" "$1" malformed_metadata\' _ "$0"\n'
    test_payload = test_payload.replace(bad, "")
    write("scripts/test-runtime-payload-verification.sh", test_payload)

    rootfs_build = read("scripts/build-ubuntu-rootfs.sh")
    rootfs_build = rootfs_build.replace(
        "# generated placeholder; minisd overwrites on ubuntu.start",
        "# generated placeholder; direct Ubuntu runtime refreshes this before use",
    )
    rootfs_build = rootfs_build.replace(
        '"note": "python3/git/curl installed on device via ubuntu.provision"',
        '"note": "python3/git/curl installed on device by the App-owned UbuntuProvisioner"',
    )
    write("scripts/build-ubuntu-rootfs.sh", rootfs_build)

    release = read("scripts/verify-android-release.sh")
    release = release.replace(
        '"$(cd "$(dirname "$0")" && pwd)/verify-runtime-payload.sh" "$APK"\n',
        '"$(cd "$(dirname "$0")" && pwd)/verify-runtime-payload.sh" "$APK"\n"$(cd "$(dirname "$0")" && pwd)/verify-root-network-proxy.sh" "$APK"\n',
        1,
    )
    write("scripts/verify-android-release.sh", release)

    commit("refactor(runtime): make Android payload rootfs-only")


def phase_remove_minisd() -> None:
    shutil.rmtree(ROOT / "src/native/minisd")
    (ROOT / "scripts/build-minisd-android.sh").unlink()
    commit("refactor(runtime): remove native minisd")


def phase_ci() -> None:
    ci = read(".github/workflows/ci.yml")
    ci = ci.replace("      minisd: ${{ steps.filter.outputs.minisd }}\n", "      network_proxy: ${{ steps.filter.outputs.network_proxy }}\n", 1)
    ci = ci.replace("          minisd=false\n", "          network_proxy=false\n", 1)
    ci = ci.replace(
        '''            case "$path" in\n              src/native/minisd/*)\n                minisd=true\n                android=true\n                ;;\n            esac\n''',
        '''            case "$path" in\n              src/native/root-network-proxy/*|scripts/build-root-network-proxy-android.sh|scripts/verify-root-network-proxy.sh)\n                network_proxy=true\n                android=true\n                ;;\n            esac\n''',
        1,
    )
    ci = ci.replace("scripts/build-minisd-android.sh|", "scripts/build-root-network-proxy-android.sh|", 2)
    ci = ci.replace("              minisd=true\n              rootfs=true", "              network_proxy=true\n              rootfs=true", 1)
    ci = ci.replace('            echo "minisd=$minisd"\n', '            echo "network_proxy=$network_proxy"\n', 1)

    start = ci.index("\n  minisd:\n")
    end = ci.index("\n  rootfs-verification:\n", start)
    proxy_job = r'''
  root-network-proxy-quality:
    name: Root network proxy quality
    needs: changes
    if: needs.changes.outputs.network_proxy == 'true'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust quality components
        run: rustup component add rustfmt clippy
      - name: Format
        run: cargo fmt --manifest-path src/native/root-network-proxy/Cargo.toml --all -- --check
      - name: Clippy
        run: cargo clippy --locked --manifest-path src/native/root-network-proxy/Cargo.toml --all-targets -- -D warnings
      - name: Test
        run: cargo test --locked --manifest-path src/native/root-network-proxy/Cargo.toml
      - name: Release build
        run: cargo build --locked --release --manifest-path src/native/root-network-proxy/Cargo.toml
'''
    ci = ci[:start] + "\n" + textwrap.dedent(proxy_job).strip("\n") + "\n" + ci[end:]
    ci = ci.replace(
        "bash -n scripts/build-ubuntu-rootfs.sh scripts/build-root-network-proxy-android.sh scripts/build-runtime-payload.sh scripts/test-build-ubuntu-rootfs-verification.sh scripts/test-runtime-payload-verification.sh scripts/verify-runtime-payload.sh scripts/verify-android-release.sh scripts/check-runtime-package-boundary.sh",
        "bash -n scripts/build-ubuntu-rootfs.sh scripts/build-root-network-proxy-android.sh scripts/build-runtime-payload.sh scripts/test-build-ubuntu-rootfs-verification.sh scripts/test-runtime-payload-verification.sh scripts/verify-runtime-payload.sh scripts/verify-root-network-proxy.sh scripts/verify-android-release.sh scripts/check-runtime-package-boundary.sh",
        1,
    )

    start = ci.index("\n  runtime-payload:\n")
    end = ci.index("\n  rclone-android:\n", start)
    runtime_jobs = r'''
  runtime-payload:
    name: Build verified Ubuntu rootfs payload
    needs: changes
    if: needs.changes.outputs.android == 'true'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Build and verify rootfs-only runtime payload
        run: bash scripts/build-runtime-payload.sh
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: android-runtime-payload
          path: |
            dist/ubuntu-arm64-rootfs.tar.gz
            dist/ubuntu-arm64-rootfs.tar.gz.sha256
            dist/ubuntu-arm64-rootfs.manifest.json
            dist/runtime-manifest.json
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  root-network-proxy-android:
    name: Build Android Root network proxy
    needs: changes
    if: needs.changes.outputs.android == 'true'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install pinned Android NDK and Rust target
        run: |
          "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "ndk;28.2.13676358"
          test -x "$ANDROID_HOME/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/28.2.13676358" >> "$GITHUB_ENV"
          rustup target add aarch64-linux-android
      - name: Build and verify Root network proxy
        run: |
          bash scripts/build-root-network-proxy-android.sh
          bash scripts/verify-root-network-proxy.sh dist
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: android-root-network-proxy
          path: |
            dist/minis-root-network-proxy-arm64-v8a
            dist/minis-root-network-proxy-arm64-v8a.sha256
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
'''
    ci = ci[:start] + "\n" + textwrap.dedent(runtime_jobs).strip("\n") + "\n" + ci[end:]

    ci = ci.replace(
        "    needs: [changes, runtime-payload, rclone-android]\n    if: needs.changes.outputs.android == 'true'\n    runs-on: ubuntu-24.04\n    steps:\n",
        "    needs: [changes, runtime-payload, root-network-proxy-android, rclone-android]\n    if: needs.changes.outputs.android == 'true'\n    runs-on: ubuntu-24.04\n    steps:\n",
        2,
    )
    download_runtime = '''      - uses: actions/download-artifact@v8.0.1\n        with:\n          name: android-runtime-payload\n          path: dist\n'''
    download_both = download_runtime + '''      - uses: actions/download-artifact@v8.0.1\n        with:\n          name: android-root-network-proxy\n          path: dist\n'''
    ci = ci.replace(download_runtime, download_both, 2)
    ci = ci.replace(
        '      - name: Verify debug APK runtime payload\n        run: bash scripts/verify-runtime-payload.sh src/android/app/build/outputs/apk/debug/app-debug.apk\n',
        '      - name: Verify debug APK runtime payload\n        run: |\n          bash scripts/verify-runtime-payload.sh src/android/app/build/outputs/apk/debug/app-debug.apk\n          bash scripts/verify-root-network-proxy.sh src/android/app/build/outputs/apk/debug/app-debug.apk\n',
        1,
    )
    ci = ci.replace(
        "    needs: [changes, runtime-payload, android-checks, android-debug-build, android-release]",
        "    needs: [changes, runtime-payload, root-network-proxy-android, android-checks, android-debug-build, android-release]",
        1,
    )
    ci = ci.replace(
        "          PAYLOAD_RESULT: ${{ needs.runtime-payload.result }}\n",
        "          PAYLOAD_RESULT: ${{ needs.runtime-payload.result }}\n          PROXY_RESULT: ${{ needs.root-network-proxy-android.result }}\n",
        1,
    )
    ci = ci.replace(
        '          if [[ "$PAYLOAD_RESULT" != "success" || "$CHECKS_RESULT" != "success" || "$BUILD_RESULT" != "success" || "$RELEASE_RESULT" != "success" ]]; then\n            echo "Android checks failed: payload=$PAYLOAD_RESULT checks=$CHECKS_RESULT build=$BUILD_RESULT release=$RELEASE_RESULT" >&2\n',
        '          if [[ "$PAYLOAD_RESULT" != "success" || "$PROXY_RESULT" != "success" || "$CHECKS_RESULT" != "success" || "$BUILD_RESULT" != "success" || "$RELEASE_RESULT" != "success" ]]; then\n            echo "Android checks failed: payload=$PAYLOAD_RESULT proxy=$PROXY_RESULT checks=$CHECKS_RESULT build=$BUILD_RESULT release=$RELEASE_RESULT" >&2\n',
        1,
    )
    write(".github/workflows/ci.yml", ci)
    commit("ci: remove minisd build and quality jobs")


def phase_guards() -> None:
    write(
        "scripts/check-runtime-package-boundary.sh",
        r'''
        #!/usr/bin/env bash
        set -euo pipefail
        cd "$(git rev-parse --show-toplevel)"
        MAIN='src/android/app/src/main/java/com/openminis/app'
        TEST='src/android/app/src/test/java/com/openminis/app'
        ANDROID_TEST='src/android/app/src/androidTest/java/com/openminis/app'
        RUNTIME="$MAIN/runtime"
        LEGACY="$MAIN/sandbox"

        fail() { echo "runtime package boundary violation: $*" >&2; exit 54; }

        for required in \
          "$RUNTIME/RuntimePathRegistry.kt" \
          "$RUNTIME/ExternalMountCoordinator.kt" \
          "$RUNTIME/ExecutionCoordinator.kt" \
          "$RUNTIME/ubuntu/UbuntuRuntime.kt" \
          "$RUNTIME/ubuntu/UbuntuKernel.kt" \
          "$RUNTIME/ubuntu/DirectRootRunner.kt" \
          "$RUNTIME/ubuntu/UbuntuPaths.kt" \
          "$RUNTIME/ubuntu/RootNetworkProxy.kt" \
          "$RUNTIME/guest/GuestCommandBridge.kt" \
          "$RUNTIME/guest/NativeOffload.kt" \
          "$RUNTIME/terminal/TerminalSanitizer.kt"; do
          [[ -f "$required" ]] || fail "missing required active component: $required"
        done

        for forbidden in \
          "$RUNTIME/minisd" \
          "$RUNTIME/RootfsManager.kt" \
          "$RUNTIME/terminal/TerminalSession.kt" \
          "$RUNTIME/MinisKernel.kt" \
          "$RUNTIME/MountedFolderCoordinator.kt"; do
          [[ ! -e "$forbidden" ]] || fail "obsolete component entered active runtime: $forbidden"
        done

        for symbol in MinisdClient MinisdProtocol MinisdBootstrap MinisdConfigBridgeServer; do
          hits="$(git grep -n -w "$symbol" -- src/android/app/src 2>/dev/null || true)"
          [[ -z "$hits" ]] || { printf '%s\n' "$hits" >&2; fail "obsolete broker type '$symbol' returned"; }
        done
        hits="$(git grep -n -E 'runtime[./]minisd|runtime\.minisd|minisd\.sock|/data/adb/minis/bin/minisd' -- src/android/app/src/main src/android/app/src/test 2>/dev/null || true)"
        [[ -z "$hits" ]] || { printf '%s\n' "$hits" >&2; fail "obsolete broker runtime contract returned"; }

        allowed_legacy_main=("$LEGACY/RootfsManager.kt" "$LEGACY/TerminalSession.kt")
        if [[ -d "$LEGACY" ]]; then
          while IFS= read -r file; do
            allowed=false
            for expected in "${allowed_legacy_main[@]}"; do [[ "$file" == "$expected" ]] && allowed=true; done
            [[ "$allowed" == true ]] || fail "unexpected active source under legacy sandbox package: $file"
          done < <(find "$LEGACY" -type f -print | sort)
        fi
        if [[ -d "$TEST/sandbox" ]]; then
          while IFS= read -r file; do
            [[ "$file" == "$TEST/sandbox/TarExtractionTest.kt" ]] || fail "unexpected unit test under legacy sandbox package: $file"
          done < <(find "$TEST/sandbox" -type f -print | sort)
        fi
        [[ ! -d "$ANDROID_TEST/sandbox" ]] || ! find "$ANDROID_TEST/sandbox" -type f -print -quit | grep -q . || fail "instrumentation tests must follow active runtime responsibilities"

        old_refs="$(git grep -n -E 'com\.openminis\.app\.sandbox\.' -- src/android 2>/dev/null || true)"
        if [[ -n "$old_refs" ]]; then
          unexpected="$(printf '%s\n' "$old_refs" | grep -Ev 'com\.openminis\.app\.sandbox\.(RootfsManager|RootfsInstallState|TerminalSession)([^A-Za-z0-9_]|$)' || true)"
          [[ -z "$unexpected" ]] || { printf '%s\n' "$unexpected" >&2; fail "unexpected legacy sandbox FQN"; }
        fi
        for legacy_name in MinisKernel MountedFolderCoordinator; do
          hits="$(git grep -n -w "$legacy_name" -- src/android/app/src 2>/dev/null || true)"
          [[ -z "$hits" ]] || { printf '%s\n' "$hits" >&2; fail "legacy runtime type name '$legacy_name' returned"; }
        done

        grep -Fq 'object RuntimePathRegistry' "$RUNTIME/RuntimePathRegistry.kt" || fail 'RuntimePathRegistry declaration missing'
        grep -Fq 'object ExternalMountCoordinator' "$RUNTIME/ExternalMountCoordinator.kt" || fail 'ExternalMountCoordinator declaration missing'
        grep -Fq 'object UbuntuKernel' "$RUNTIME/ubuntu/UbuntuKernel.kt" || fail 'UbuntuKernel declaration missing'
        grep -Fq 'object RootNetworkProxy' "$RUNTIME/ubuntu/RootNetworkProxy.kt" || fail 'Root network proxy boundary missing'
        grep -Fq 'const val PROXY_LISTEN = "127.0.0.1:18787"' "$RUNTIME/ubuntu/RootNetworkProxy.kt" || fail 'Root network proxy loopback contract changed'
        grep -Fq 'const val HOST_ROOTFS = "/data/adb/minis/rootfs"' "$RUNTIME/ubuntu/UbuntuPaths.kt" || fail 'rootfs contract changed'
        grep -Fq 'LEGACY_WORKSPACE = "/data/adb/minis/workspace"' "$RUNTIME/ubuntu/UbuntuPaths.kt" || fail 'legacy workspace migration contract changed'
        grep -Fq 'Bind(workspace.absolutePath, "/workspace")' "$RUNTIME/ubuntu/UbuntuKernel.kt" || fail 'guest workspace bind contract changed'
        grep -Fq -- '--reuid=$uid --regid=$uid --clear-groups' "$RUNTIME/ubuntu/UbuntuKernel.kt" || fail 'guest App UID drop missing'
        grep -Fq -- '--inh-caps=-all --ambient-caps=-all --bounding-set=-all' "$RUNTIME/ubuntu/UbuntuKernel.kt" || fail 'guest capability drop missing'
        if grep -Eiq 'proot|proot -b' "$RUNTIME/ExternalMountCoordinator.kt"; then fail "ExternalMountCoordinator documents removed PRoot semantics"; fi
        if grep -Eiq 'minisd|broker-owned' "$RUNTIME/ExternalMountCoordinator.kt"; then fail "ExternalMountCoordinator documents removed broker semantics"; fi

        echo 'runtime package boundary contract: OK'
        ''',
    )

    write(
        "scripts/check_build_cleanup.py",
        r'''
        #!/usr/bin/env python3
        """Reject obsolete build paths without banning provenance or migration-only identity."""
        from __future__ import annotations
        import re
        import sys
        from pathlib import Path

        REQUIRED_PATHS = (
            "src/android/gradlew",
            "src/android/app/build.gradle.kts",
            "src/native/root-network-proxy/Cargo.toml",
            "scripts/build-root-network-proxy-android.sh",
            "scripts/build-android-debug.ps1",
            "scripts/build-ubuntu-rootfs.sh",
            "scripts/verify-android-release.sh",
        )
        FORBIDDEN_PATHS = (
            "src/native/minisd",
            "scripts/build-minisd-android.sh",
            "scripts/build-pet-apk.ps1",
            "scripts/verify_models_dev_resolution.py",
        )
        ROOT_ACTIVE_DOCS = ("README.md", "README.zh-CN.md", "BUILDING.md", "BUILDING.zh-CN.md", "CONTRIBUTING.md")
        SCRIPT_SUFFIXES = {".sh", ".ps1", ".py"}
        SELF_EXCLUDED_SCRIPTS = {"scripts/check_build_cleanup.py", "scripts/test_build_cleanup_guard.py"}
        LEGACY_IOS_RE = re.compile(r'''(?i)(?:^|[\\/\s'"`])src[\\/]ios(?:[\\/\s'"`]|$)''')
        LEGACY_WRAPPER_RE = re.compile(r"(?i)build-pet-apk\.ps1")
        ACTIVE_MINISD_RE = re.compile(r"(?i)(?:src/native/minisd|build-minisd-android|libminisd\.so|minisd-arm64-v8a|runtime\.minisd|minisd\.sock)")
        UPSTREAM_CLONE_RE = re.compile(r"(?is)\bgit\s+clone\b[^\n]*(?:github\.com[/:]OpenMinis/OpenMinis(?:\.git)?|\bOpenMinisPet\b)")
        UPSTREAM_PATCH_RE = re.compile(r"(?is)(?:\bgit\s+apply\b|\bpatch\b)[^\n]*(?:OpenMinis|OpenMinisPet)")

        def _active_files(root: Path) -> list[Path]:
            files: set[Path] = set()
            for relative in ROOT_ACTIVE_DOCS:
                path = root / relative
                if path.is_file(): files.add(path)
            scripts = root / "scripts"
            if scripts.is_dir():
                for path in scripts.iterdir():
                    if path.is_file() and path.suffix.lower() in SCRIPT_SUFFIXES and path.relative_to(root).as_posix() not in SELF_EXCLUDED_SCRIPTS:
                        files.add(path)
            workflows = root / ".github" / "workflows"
            if workflows.is_dir():
                for pattern in ("*.yml", "*.yaml"):
                    files.update(path for path in workflows.glob(pattern) if path.is_file())
            return sorted(files)

        def check_repository(root: Path) -> list[str]:
            root = root.resolve(); errors: list[str] = []
            for relative in REQUIRED_PATHS:
                if not (root / relative).is_file(): errors.append(f"missing canonical build path: {relative}")
            for relative in FORBIDDEN_PATHS:
                if (root / relative).exists(): errors.append(f"obsolete build path exists: {relative}")
            for path in _active_files(root):
                relative = path.relative_to(root).as_posix()
                try: text = path.read_text(encoding="utf-8")
                except UnicodeDecodeError:
                    errors.append(f"active tooling is not UTF-8 text: {relative}"); continue
                if LEGACY_WRAPPER_RE.search(text): errors.append(f"legacy build wrapper referenced by active tooling: {relative}")
                if LEGACY_IOS_RE.search(text): errors.append(f"removed iOS source path referenced by active tooling: {relative}")
                if ACTIVE_MINISD_RE.search(text): errors.append(f"obsolete minisd build/runtime path referenced by active tooling: {relative}")
                if UPSTREAM_CLONE_RE.search(text): errors.append(f"obsolete upstream clone pipeline referenced by active tooling: {relative}")
                if UPSTREAM_PATCH_RE.search(text): errors.append(f"obsolete upstream patch pipeline referenced by active tooling: {relative}")
            return errors

        def main(argv: list[str]) -> int:
            root = Path(argv[1]) if len(argv) > 1 else Path(__file__).resolve().parents[1]
            errors = check_repository(root)
            if errors:
                for error in errors: print(f"build-cleanup guard: {error}", file=sys.stderr)
                return 1
            print("build-cleanup guard passed"); return 0
        if __name__ == "__main__": raise SystemExit(main(sys.argv))
        ''',
    )

    tests = read("scripts/test_build_cleanup_guard.py")
    insertion = '''\n    def test_minisd_paths_are_rejected(self) -> None:\n        root = self.make_repo()\n        obsolete = root / "src/native/minisd"\n        obsolete.mkdir(parents=True, exist_ok=True)\n        (obsolete / "Cargo.toml").write_text("[package]\\nname='minisd'\\n", encoding="utf-8")\n        self.assertTrue(any("obsolete build path exists" in error for error in GUARD.check_repository(root)))\n\n    def test_minisd_tooling_reference_is_rejected(self) -> None:\n        root = self.make_repo()\n        (root / "scripts/tool.sh").write_text("bash scripts/build-minisd-android.sh\\n", encoding="utf-8")\n        self.assertTrue(any("obsolete minisd build/runtime path" in error for error in GUARD.check_repository(root)))\n'''
    tests = tests.replace("\n    def test_migration_only_package_identity_is_allowed", insertion + "\n    def test_migration_only_package_identity_is_allowed", 1)
    write("scripts/test_build_cleanup_guard.py", tests)

    bundle = read("scripts/verify-android-bundle.sh")
    bundle = bundle.replace("compressed JNI packaging required for minisd", "materialized JNI packaging required for the Root network proxy")
    write("scripts/verify-android-bundle.sh", bundle)
    commit("test(runtime): enforce direct Ubuntu boundary")


def phase_docs() -> None:
    readme = read("README.md")
    readme = readme.replace(
        "**Minis for Android** is an independent AI agent runtime for rooted Android devices: a native Android app, a Rust root broker (`minisd`), and Ubuntu 24.04 userspace sharing the Android kernel. It is not a VM.\n\n```text\nAndroid app → Unix socket RPC → minisd → mount namespace + bind mounts + chroot → Ubuntu 24.04\n```",
        "**Minis for Android** is an independent AI agent runtime for rooted Android devices: a native Android app and Ubuntu 24.04 userspace sharing the Android kernel. It is not a VM. The App owns runtime/session lifecycle; Root is bounded to mount/chroot maintenance plus a loopback-only outbound network proxy.\n\n```text\nAndroid app → ExecutionCoordinator → RootPersistentShell → UbuntuKernel → su → unshare -m → bind mounts → chroot → setpriv(App UID) → bash\n```",
        1,
    )
    readme = readme.replace("- Sandbox DNS refresh flow implemented through `ubuntu.refreshDns` RPC and runtime DNS discovery.\n", "- Direct Ubuntu DNS refresh and App-owned rootfs provisioning are implemented without a runtime RPC daemon.\n")
    write("README.md", readme)

    zh = read("README.zh-CN.md")
    zh = zh.replace(
        "面向 **已 Root 的 Android 设备** 的 AI Agent Runtime。原生 Android App + Rust `minisd` + Ubuntu 24.04 userspace，共用 Android 内核，不是虚拟机。",
        "面向 **已 Root 的 Android 设备** 的 AI Agent Runtime。原生 Android App + Ubuntu 24.04 userspace，共用 Android 内核，不是虚拟机。App 直接持有运行时与会话生命周期。",
        1,
    )
    start = zh.index("```text\nAndroid 原生 App\n")
    end = zh.index("\n```", start) + 4
    zh = zh[:start] + """```text\nAndroid 原生 App\n  ↓\nExecutionCoordinator → RootPersistentShell → UbuntuKernel\n  ↓\nsu → unshare -m → bind mount → chroot\n  ↓\nsetpriv(App UID, capabilities=none) → bash\n  ↓\nUbuntu 24.04 userspace\n```""" + zh[end:]
    zh = zh.replace(
        "App 负责会话、Provider、工具权限与审批；`minisd` 负责特权 Linux 边界、持久化布局、namespace/mount/chroot 与 guest 执行。Guest 命令使用运行时取得的真实 App guest UID/GID，禁止写死 `10000`。",
        "App 负责会话、Provider、工具权限与审批，并直接持有 Ubuntu shell 生命周期。Root 仅用于 mount namespace、bind mount、chroot、rootfs 维护以及单一职责的 loopback 出站代理；普通 Guest 命令最终必须降到真实 App UID/GID 且清空 capabilities。",
        1,
    )
    zh = zh.replace("核心 Root/minisd/Ubuntu 与 `/data/adb/minis` 架构已经形成。", "Direct Root/Ubuntu 与 `/data/adb/minis` 架构已经形成。")
    write("README.zh-CN.md", zh)

    building = read("BUILDING.md")
    building = building.replace("Gradle, minisd and rclone default to NDK", "Gradle, the Root network proxy and rclone default to NDK")
    building = building.replace("the minisd/Ubuntu runtime remains arm64-only", "the Root network proxy/Ubuntu runtime remains arm64-only")
    section_start = building.index("## 3. Build `minisd`")
    section_end = building.index("## 4. Build the Ubuntu rootfs", section_start)
    building = building[:section_start] + '''## 3. Build the Root network proxy\n\n```bash\nrustup target add aarch64-linux-android\nbash scripts/build-root-network-proxy-android.sh\n```\n\nThis binary has one responsibility: expose `127.0.0.1:18787` so App-UID Ubuntu guests can use Root egress on Android/VPN configurations that restrict non-Root outbound sockets. It has no RPC or command-execution API.\n\n''' + building[section_end:]
    building = building.replace(
        "This writes `dist/minisd-arm64-v8a`, `dist/ubuntu-arm64-rootfs.tar.gz`, and `dist/runtime-manifest.json`. Gradle packages the three files together; partial payloads are rejected. Source-only local builds may omit all three and fail closed on the device, while CI requires and verifies the complete payload in every assembled APK.",
        "This writes the rootfs-only payload: `dist/ubuntu-arm64-rootfs.tar.gz` and `dist/runtime-manifest.json`. Build `scripts/build-root-network-proxy-android.sh` separately; Gradle stages its verified ELF independently as `libminisnetproxy.so`. CI requires both the rootfs payload and proxy for assembled APKs.",
        1,
    )
    building = building.replace(
        '''Rust quality checks:\n\n```bash\ncargo fmt --manifest-path src/native/minisd/Cargo.toml --all -- --check\ncargo clippy --locked --manifest-path src/native/minisd/Cargo.toml --all-targets -- -D warnings\ncargo test --locked --manifest-path src/native/minisd/Cargo.toml\n```''',
        '''Root network proxy Rust quality checks:\n\n```bash\ncargo fmt --manifest-path src/native/root-network-proxy/Cargo.toml --all -- --check\ncargo clippy --locked --manifest-path src/native/root-network-proxy/Cargo.toml --all-targets -- -D warnings\ncargo test --locked --manifest-path src/native/root-network-proxy/Cargo.toml\n```''',
        1,
    )
    runtime_start = building.index("## Runtime notes")
    trouble = building.index("## Troubleshooting", runtime_start)
    runtime_notes = '''## Runtime notes\n\nThe rooted-device Linux path is:\n\n```text\nAndroid App\n  ↓\nExecutionCoordinator → RootPersistentShell → UbuntuKernel\n  ↓\nsu → unshare -m → bind mounts → chroot\n  ↓\nsetpriv(App UID, no capabilities) → Ubuntu 24.04 bash\n```\n\nThe App owns persistent user data and per-session shells. Root is used only for mount/chroot/rootfs maintenance and the loopback-only outbound network proxy. Existing data under `/data/adb/minis/{workspace,sessions,memory,skills,shared,home}` is migrated into App-owned storage; resetting the rootfs must not delete user data.\n\n'''
    building = building[:runtime_start] + runtime_notes + building[trouble:]
    building = building.replace("then inspect `minisd` status and application logs.", "then inspect direct Ubuntu/runtime and Root network proxy application logs.")
    write("BUILDING.md", building)

    bzh = read("BUILDING.zh-CN.md")
    bzh = bzh.replace("Gradle、minisd 与 rclone 默认使用 NDK", "Gradle、Root 网络代理与 rclone 默认使用 NDK")
    s = bzh.index("## 3. 构建 `minisd`")
    e = bzh.index("## 4. 构建 Ubuntu rootfs", s)
    bzh = bzh[:s] + '''## 3. 构建 Root 网络代理\n\n打包前还需构建并导入 rclone（包含 arm64-v8a 与 x86_64）：\n\n```bash\nbash deps/build_rclone_android.sh\nmkdir -p src/android/app/libs\ncp deps/build/rclone/rclone.aar src/android/app/libs/rclone.aar\n```\n\nRoot 网络代理只负责 `127.0.0.1:18787` 的 HTTP/CONNECT 出站转发，不提供 RPC 或任意 Root 命令接口：\n\n```bash\nrustup target add aarch64-linux-android\nbash scripts/build-root-network-proxy-android.sh\n```\n\n''' + bzh[e:]
    bzh = bzh.replace(
        "脚本输出 `dist/minisd-arm64-v8a`、`dist/ubuntu-arm64-rootfs.tar.gz` 和 `dist/runtime-manifest.json`。Gradle 只允许三项一起打包，拒绝部分载荷。纯源码本地构建可以全部省略并在设备上 fail-closed；CI 组装的每个 APK 则强制包含并验证完整载荷。",
        "该脚本只输出 rootfs payload：`dist/ubuntu-arm64-rootfs.tar.gz` 和 `dist/runtime-manifest.json`。Root 网络代理由 `build-root-network-proxy-android.sh` 独立构建和校验，Gradle 以 `libminisnetproxy.so` 单独打包；CI 组装 APK 时两者都必须存在。",
        1,
    )
    bzh = bzh.replace(
        '''Rust：\n\n```bash\ncargo fmt --manifest-path src/native/minisd/Cargo.toml --all -- --check\ncargo clippy --locked --manifest-path src/native/minisd/Cargo.toml --all-targets -- -D warnings\ncargo test --locked --manifest-path src/native/minisd/Cargo.toml\n```''',
        '''Root 网络代理 Rust：\n\n```bash\ncargo fmt --manifest-path src/native/root-network-proxy/Cargo.toml --all -- --check\ncargo clippy --locked --manifest-path src/native/root-network-proxy/Cargo.toml --all-targets -- -D warnings\ncargo test --locked --manifest-path src/native/root-network-proxy/Cargo.toml\n```''',
        1,
    )
    s = bzh.index("## 当前 Linux 执行路径")
    e = bzh.index("更多内容：", s)
    bzh = bzh[:s] + '''## 当前 Linux 执行路径\n\n```text\nAndroid App\n  ↓\nExecutionCoordinator → RootPersistentShell → UbuntuKernel\n  ↓\nsu → unshare -m → bind mount → chroot\n  ↓\nsetpriv(App UID, capabilities=none) → Ubuntu 24.04 bash\n```\n\nApp 直接持有会话 shell。Root 仅用于 mount/chroot/rootfs 维护和 loopback-only 出站代理；普通 guest 命令不会以 UID 0 执行。旧 `/data/adb/minis/{workspace,sessions,memory,skills,shared,home}` 数据只做一次迁移，rootfs reset 不得删除用户数据。\n\n''' + bzh[e:]
    write("BUILDING.zh-CN.md", bzh)

    contrib = read("CONTRIBUTING.md")
    contrib = contrib.replace(
        "Linux runtime: `minisd`, mount namespace, chroot, Ubuntu 24.04, persistent data under `/data/adb/minis`.",
        "Linux runtime: App-owned direct Ubuntu sessions using mount namespace + chroot + App-UID privilege drop, with persistent data migration from `/data/adb/minis`.",
        1,
    )
    write("CONTRIBUTING.md", contrib)
    commit("docs(runtime): describe direct Ubuntu architecture")


def acceptance_and_cleanup() -> None:
    # Remove all one-off refactor scaffolding in the working tree before testing,
    # so the tested tree is exactly the tree committed by the final cleanup commit.
    for path in [
        ".github/workflows/tmp-direct-runtime-inventory.yml",
        ".github/scripts/phase1_direct_runtime_patch.py",
        ".github/scripts/phase2a_direct_runtime_cleanup.py",
        ".github/scripts/phase2b_direct_guest_bridge.py",
        ".github/scripts/phase2c_wire_provisioner.py",
        ".github/scripts/phase3_direct_runtime_cleanup.py",
    ]:
        target = ROOT / path
        if target.is_file(): target.unlink()

    run("git", "diff", "--check")
    run("python3", "scripts/test_build_cleanup_guard.py")
    run("python3", "scripts/check_build_cleanup.py")
    run("bash", "scripts/test-build-ubuntu-rootfs-verification.sh")
    run("bash", "scripts/test-runtime-payload-verification.sh")
    run("bash", "scripts/check-runtime-package-boundary.sh")
    run("cargo", "fmt", "--manifest-path", "src/native/root-network-proxy/Cargo.toml", "--all", "--", "--check")
    run("cargo", "clippy", "--locked", "--manifest-path", "src/native/root-network-proxy/Cargo.toml", "--all-targets", "--", "-D", "warnings")
    run("cargo", "test", "--locked", "--manifest-path", "src/native/root-network-proxy/Cargo.toml")

    # Full Android acceptance requires the same native prerequisites as canonical CI.
    sdkmanager = Path(os.environ["ANDROID_HOME"]) / "cmdline-tools/latest/bin/sdkmanager"
    run(str(sdkmanager), "ndk;28.2.13676358")
    ndk = Path(os.environ["ANDROID_HOME"]) / "ndk/28.2.13676358"
    os.environ["ANDROID_NDK_HOME"] = str(ndk)
    run("rustup", "target", "add", "aarch64-linux-android")
    run("bash", "scripts/build-root-network-proxy-android.sh")
    run("bash", "scripts/verify-root-network-proxy.sh", "dist")
    run("bash", "scripts/build-runtime-payload.sh")

    # rclone AAR required by every Android compile in this repository.
    gopath = subprocess.check_output(["go", "env", "GOPATH"], text=True).strip()
    env = {"PATH": f"{gopath}/bin:{os.environ['PATH']}"}
    run("go", "install", "golang.org/x/mobile/cmd/gomobile@f98cc9b", env=env)
    run("gomobile", "init", env=env)
    run("bash", "deps/build_rclone_android.sh", env=env)
    libs = ROOT / "src/android/app/libs"
    libs.mkdir(parents=True, exist_ok=True)
    shutil.copy2(ROOT / "deps/build/rclone/rclone.aar", libs / "rclone.aar")

    android = ROOT / "src/android"
    gradle_env = {"MINIS_REQUIRE_RUNTIME_PAYLOAD": "1"}
    run("./gradlew", ":app:compileDebugKotlin", "--max-workers=4", "--stacktrace", cwd=android, env=gradle_env)
    run("./gradlew", ":app:testDebugUnitTest", "--max-workers=4", "--stacktrace", cwd=android, env=gradle_env)
    run("./gradlew", ":app:assembleDebug", "--max-workers=4", "--stacktrace", cwd=android, env=gradle_env)
    apk = "src/android/app/build/outputs/apk/debug/app-debug.apk"
    run("bash", "scripts/verify-runtime-payload.sh", apk)
    run("bash", "scripts/verify-root-network-proxy.sh", apk)
    run("bash", "scripts/verify-android-16k.sh", apk)

    grep = subprocess.run(
        ["git", "grep", "-n", "-E", "minisd|Minisd|libminisd\\.so|minisd-arm64-v8a|runtime\\.minisd|minisd\\.sock"],
        cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    print("=== final minisd grep ===")
    print(grep.stdout)
    forbidden = []
    for line in grep.stdout.splitlines():
        path = line.split(":", 1)[0]
        if path.startswith(("src/android/", "scripts/", ".github/workflows/")):
            forbidden.append(line)
    if forbidden:
        print("Forbidden active minisd references remain:", *forbidden, sep="\n", file=sys.stderr)
        raise SystemExit(1)

    commit("chore: remove direct-runtime refactor scaffolding")


def main() -> None:
    os.chdir(ROOT)
    run("git", "config", "user.name", "github-actions[bot]")
    run("git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com")
    branch = subprocess.check_output(["git", "branch", "--show-current"], cwd=ROOT, text=True).strip()
    if branch != BRANCH:
        raise SystemExit(f"refusing to run on {branch!r}; expected {BRANCH}")
    phase_payload_and_network_proxy()
    phase_remove_minisd()
    phase_ci()
    phase_guards()
    phase_docs()
    acceptance_and_cleanup()


if __name__ == "__main__":
    main()
