package com.openminis.app.provider.openai

import com.openminis.app.data.model.AgentContentPart
import com.openminis.app.data.model.LLMMessage

/** OpenAI assistant messages cannot carry input images. Replay generated pixels
 * as explicitly labelled context on the next user/tool-result message. */
internal fun replayGeneratedImages(messages: List<LLMMessage>): List<LLMMessage> {
    val pending = mutableListOf<AgentContentPart.ImageData>()
    val result = mutableListOf<LLMMessage>()
    for (message in messages) {
        if (message.role == LLMMessage.Role.ASSISTANT) {
            val images = message.contentParts.filterIsInstance<AgentContentPart.ImageData>() +
                message.imageParts.map { AgentContentPart.ImageData(it.data, it.mimeType, it.linuxPath, it.noVisionPlaceholder) }
            if (images.isEmpty()) { result += message; continue }
            pending += images
            val parts = message.contentParts.filterNot { it is AgentContentPart.ImageData }.ifEmpty {
                listOf(AgentContentPart.Text(message.content.ifBlank { "[Assistant generated an image.]" }))
            }
            result += message.copy(contentParts = parts, imageParts = emptyList())
        } else if (pending.isNotEmpty()) {
            val parts = message.contentParts.ifEmpty {
                if (message.content.isNotEmpty()) listOf(AgentContentPart.Text(message.content)) else emptyList()
            }
            result += message.copy(contentParts = parts +
                AgentContentPart.Text("[Context: the following images were generated by the assistant in the preceding turn.]") + pending)
            pending.clear()
        } else result += message
    }
    if (pending.isNotEmpty()) result += LLMMessage(LLMMessage.Role.USER, "", contentParts =
        listOf(AgentContentPart.Text("[Context: images generated by the assistant in the preceding turn.]")) + pending)
    return result
}
