package com.openminis.app.sandbox

import android.content.Context
import android.net.ConnectivityManager
import android.net.LinkProperties
import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FilterInputStream
import java.io.InputStream
import java.nio.charset.Charset

/**
 * Observable state for rootfs installation. Kept for UI compatibility;
 * Ubuntu rootfs is managed by minisd, so install state is always Installed.
 */
sealed class RootfsInstallState {
    object Idle : RootfsInstallState()
    object Preparing : RootfsInstallState()
    data class Extracting(val progress: Float) : RootfsInstallState()
    object Finalizing : RootfsInstallState()
    object Installed : RootfsInstallState()
    data class Failed(val error: String) : RootfsInstallState()
}

/**
 * P2: Alpine rootfs removed; on-device Ubuntu rootfs is managed by minisd
 * under /data/adb/minis/rootfs. This class is a compatibility shell for the
 * sandbox UI and the POSIX tar parser used by tests. No Alpine install paths.
 */
class RootfsManager private constructor(private val context: Context) {

    // Ubuntu rootfs is managed by minisd (host path /data/adb/minis/rootfs);
    // kept as a stub for UI compatibility — install state is always Installed.
    val rootfsDir: File = File(com.openminis.app.sandbox.ubuntu.UbuntuPaths.HOST_ROOTFS)

    val isInstalled: Boolean
        get() = true

    private val _installState = MutableStateFlow<RootfsInstallState>(RootfsInstallState.Installed)
    val installState: StateFlow<RootfsInstallState> = _installState.asStateFlow()

    suspend fun installIfNeeded() = withContext(Dispatchers.IO) {
        _installState.value = RootfsInstallState.Installed
        Unit
    }

    suspend fun installProotIfNeeded() = withContext(Dispatchers.IO) {
        Unit
    }

    suspend fun reset(keepUserData: Boolean = false): File? = withContext(Dispatchers.IO) {
        null
    }

    suspend fun getRootfsSize(): Long = withContext(Dispatchers.IO) { 0L }

    suspend fun restoreUserData(backupDir: File) = withContext(Dispatchers.IO) { Unit }

    fun ensureSessionDirs(sessionId: String) {
        com.openminis.app.sandbox.ubuntu.UbuntuPaths.ensureSessionDirs(sessionId)
    }

    /** DNS is generated by minisd on ubuntu.start; kept as no-op for callers. */
    fun refreshDns() {
        Unit
    }

    suspend fun applyDefaultMountOverlay() = withContext(Dispatchers.IO) { Unit }

    // --- POSIX tar extraction (kept for TarExtractionTest) ---

    internal fun extractTar(input: InputStream, targetDir: File) {
        val header = ByteArray(512)
        while (true) {
            val bytesRead = readFully(input, header)
            if (bytesRead < 512) break
            if (header.all { it == 0.toByte() }) break
            val name = extractString(header, 0, 100)
            val modeOctal = extractString(header, 100, 8)
            val sizeOctal = extractString(header, 124, 12)
            val typeFlag = header[156].toInt().toChar()
            val linkName = extractString(header, 157, 100)
            val mode = modeOctal.trim().toIntOrNull(8) ?: 0
            val prefix = extractString(header, 345, 155)
            val fullName = if (prefix.isNotEmpty()) "$prefix/$name" else name
            if (fullName.isEmpty()) break
            val size = sizeOctal.trim().toLongOrNull(8) ?: 0L
            val outFile = File(targetDir, fullName)
            when (typeFlag) {
                '5', 'D' -> outFile.mkdirs()
                '2' -> {
                    outFile.parentFile?.mkdirs()
                    try {
                        java.nio.file.Files.createSymbolicLink(
                            outFile.toPath(),
                            java.nio.file.Paths.get(linkName)
                        )
                    } catch (_: Exception) {
                        Log.w(TAG, "Failed to create symlink: $fullName -> $linkName")
                    }
                }
                '0', '\u0000' -> {
                    outFile.parentFile?.mkdirs()
                    outFile.outputStream().use { output ->
                        var remaining = size
                        val buf = ByteArray(8192)
                        while (remaining > 0) {
                            val toRead = minOf(buf.size.toLong(), remaining).toInt()
                            val n = input.read(buf, 0, toRead)
                            if (n < 0) break
                            output.write(buf, 0, n)
                            remaining -= n
                        }
                    }
                    if (mode and 0b001_001_001 != 0) {
                        outFile.setExecutable(true, false)
                    }
                    val remainder = (size % 512).toInt()
                    if (remainder != 0) {
                        skipFully(input, (512 - remainder).toLong())
                    }
                    continue
                }
                '1' -> {
                    outFile.parentFile?.mkdirs()
                    val linkTarget = File(targetDir, linkName)
                    if (linkTarget.exists()) {
                        linkTarget.copyTo(outFile, overwrite = true)
                    }
                }
                else -> {}
            }
            if (typeFlag != '0' && typeFlag != '\u0000' && size > 0) {
                val blocks = (size + 511) / 512 * 512
                skipFully(input, blocks)
            }
        }
    }

    internal fun extractString(header: ByteArray, offset: Int, length: Int): String {
        val end = minOf(offset + length, header.size)
        var actualEnd = offset
        for (i in offset until end) {
            if (header[i] == 0.toByte()) break
            actualEnd = i + 1
        }
        return String(header, offset, actualEnd - offset, Charset.forName("UTF-8"))
    }

    internal fun readFully(input: InputStream, buf: ByteArray): Int {
        var offset = 0
        while (offset < buf.size) {
            val n = input.read(buf, offset, buf.size - offset)
            if (n < 0) return offset
            offset += n
        }
        return offset
    }

    internal fun skipFully(input: InputStream, count: Long) {
        var remaining = count
        val buf = ByteArray(8192)
        while (remaining > 0) {
            val toRead = minOf(buf.size.toLong(), remaining).toInt()
            val n = input.read(buf, 0, toRead)
            if (n < 0) break
            remaining -= n
        }
    }

    companion object {
        private const val TAG = "RootfsManager"
        private var instance: RootfsManager? = null
        fun getInstance(context: Context): RootfsManager {
            return instance ?: RootfsManager(context.applicationContext).also { instance = it }
        }
    }
}
