use std::collections::BTreeMap;

pub const GUEST_PATH: &str =
    "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin";
pub const PROXY_KEYS: &[&str] = &[
    "http_proxy",
    "https_proxy",
    "HTTP_PROXY",
    "HTTPS_PROXY",
    "ALL_PROXY",
    "all_proxy",
    "no_proxy",
    "NO_PROXY",
];
pub const PROXY_NO_PROXY: &str = "localhost,127.0.0.1,::1";
pub const FALLBACK_DNS: &[&str] = &["8.8.8.8", "8.8.4.4"];
/// Dynamic-linker keys that a guest could use to escape the sandbox via
/// preloaded/injected libraries. Filtered at the single chokepoint in
/// `guest_env`; the filter is case-sensitive (ld.so only honors these exact
/// names).
pub const DANGEROUS_ENV_KEYS: &[&str] = &[
    "LD_PRELOAD",
    "LD_LIBRARY_PATH",
    "LD_AUDIT",
    "LD_DEBUG",
    "LD_ORIGIN_PATH",
    "LD_PROFILE",
];

/// POSIX TZ from Android `date +%z` / ISO offset (`+0800`, `-0530`).
/// UTC+8 → `LCL-8` (sign inverted; fixed name avoids musl `GMT+8` parse).
pub fn posix_tz_from_offset(offset: &str) -> Option<String> {
    let s = offset.trim();
    if s.len() < 3 {
        return None;
    }
    let (sign_ch, rest) = s.split_at(1);
    let sign = match sign_ch {
        "+" | "-" => sign_ch,
        _ => return None,
    };
    let digits: String = rest.chars().filter(|c| c.is_ascii_digit()).collect();
    if digits.len() < 2 {
        return None;
    }
    let hours: i32 = digits.get(0..2)?.parse().ok()?;
    let mins: i32 = if digits.len() >= 4 {
        digits.get(2..4)?.parse().ok()?
    } else {
        0
    };
    if hours > 14 || mins > 59 {
        return None;
    }
    let posix_sign = if sign == "+" { "-" } else { "+" };
    if mins == 0 {
        Some(format!("LCL{posix_sign}{hours}"))
    } else {
        Some(format!("LCL{posix_sign}{hours}:{mins:02}"))
    }
}

pub fn parse_nameservers_from_resolv(text: &str) -> Vec<String> {
    text.lines()
        .filter_map(|l| l.trim().strip_prefix("nameserver"))
        .map(str::trim)
        .filter(|s| !s.is_empty() && *s != "127.0.0.1" && *s != "::1")
        .map(|s| s.to_string())
        .collect()
}

pub fn parse_dumpsys_dns(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    for line in text.lines() {
        let lower = line.to_ascii_lowercase();
        if !(lower.contains("dnsaddresses")
            || lower.contains("dnsservers")
            || lower.contains("dns server"))
        {
            continue;
        }
        for token in line.split(|c: char| !c.is_ascii_hexdigit() && c != '.' && c != ':') {
            if token.is_empty() {
                continue;
            }
            if token.parse::<std::net::Ipv4Addr>().is_ok()
                || token.parse::<std::net::Ipv6Addr>().is_ok()
            {
                if token != "127.0.0.1" && token != "::1" && !out.iter().any(|s| s == token) {
                    out.push(token.to_string());
                }
            }
        }
    }
    out
}

pub fn build_resolv_conf(nameservers: &[String], search: Option<&str>) -> String {
    let mut s = String::from("# generated by minisd\n");
    if let Some(search) = search {
        if !search.is_empty() {
            s.push_str("search ");
            s.push_str(search);
            s.push('\n');
        }
    }
    let servers: Vec<&str> = if nameservers.is_empty() {
        FALLBACK_DNS.to_vec()
    } else {
        nameservers.iter().map(String::as_str).collect()
    };
    for ns in servers {
        s.push_str("nameserver ");
        s.push_str(ns);
        s.push('\n');
    }
    s
}

pub fn proxy_block(proxy_uri: &str) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let uri = proxy_uri.trim();
    for key in PROXY_KEYS {
        let value = match *key {
            "no_proxy" | "NO_PROXY" => {
                if uri.is_empty() {
                    String::new()
                } else {
                    PROXY_NO_PROXY.to_string()
                }
            }
            _ => uri.to_string(),
        };
        out.insert((*key).to_string(), value);
    }
    out
}

pub fn guest_env(
    tz: &str,
    proxy_uri: &str,
    home: &str,
    extra: &BTreeMap<String, String>,
) -> BTreeMap<String, String> {
    let mut env = BTreeMap::new();
    env.insert("PATH".into(), GUEST_PATH.into());
    env.insert("HOME".into(), home.into());
    env.insert("USER".into(), "minis".into());
    env.insert("LOGNAME".into(), "minis".into());
    env.insert("SHELL".into(), "/bin/bash".into());
    env.insert("LANG".into(), "C.UTF-8".into());
    env.insert("LC_ALL".into(), "C.UTF-8".into());
    env.insert("CHARSET".into(), "UTF-8".into());
    env.insert("TERM".into(), "xterm-256color".into());
    env.insert("NO_COLOR".into(), "1".into());
    env.insert("PYTHONDONTWRITEBYTECODE".into(), "1".into());
    env.insert("GOMAXPROCS".into(), "2".into());
    env.insert("TZ".into(), tz.to_string());
    env.extend(proxy_block(proxy_uri));
    for (k, v) in extra {
        // Security filter, single chokepoint: silently drop dangerous
        // dynamic-linker keys (LD_PRELOAD etc.) so guests cannot inject
        // libraries or override the loader. Never panics, just skips.
        if DANGEROUS_ENV_KEYS.contains(&k.as_str()) {
            continue;
        }
        env.insert(k.clone(), v.clone());
    }
    env
}

pub fn discover_dns() -> Vec<String> {
    let mut found = Vec::new();
    if let Ok(text) = std::fs::read_to_string("/etc/resolv.conf") {
        found.extend(parse_nameservers_from_resolv(&text));
    }
    for key in [
        "net.dns1",
        "net.dns2",
        "net.dns3",
        "dhcp.wlan0.dns1",
        "dhcp.wlan0.dns2",
        "dhcp.eth0.dns1",
    ] {
        if let Some(v) = getprop(key) {
            if !v.is_empty() && v != "0.0.0.0" && !found.iter().any(|s| s == &v) {
                found.push(v);
            }
        }
    }
    found
}

pub fn discover_tz() -> String {
    if let Some(off) = run_first_line("/system/bin/date", &["+%z"]) {
        if let Some(tz) = posix_tz_from_offset(&off) {
            return tz;
        }
    }
    if let Some(name) = getprop("persist.sys.timezone") {
        if !name.is_empty() {
            return name;
        }
    }
    "LCL-8".into()
}

pub fn discover_proxy() -> String {
    if let Some(v) = run_first_line("/system/bin/settings", &["get", "global", "http_proxy"]) {
        let v = v.trim().to_string();
        if !v.is_empty() && v != "null" && v != ":0" && v != "none" {
            if v.starts_with("http://") || v.starts_with("https://") {
                return v;
            }
            return format!("http://{v}");
        }
    }
    if let Some(v) = getprop("http.proxy") {
        if !v.is_empty() && v != "null" {
            if v.starts_with("http://") {
                return v;
            }
            return format!("http://{v}");
        }
    }
    String::new()
}

pub fn getprop(key: &str) -> Option<String> {
    run_first_line("/system/bin/getprop", &[key]).filter(|s| !s.is_empty())
}

fn run_first_line(bin: &str, args: &[&str]) -> Option<String> {
    let out = std::process::Command::new(bin).args(args).output().ok()?;
    if !out.status.success() && out.stdout.is_empty() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout);
    s.lines().next().map(|l| l.trim().to_string())
}

pub fn write_resolv_conf(rootfs: &str, nameservers: &[String]) -> Result<String, String> {
    let body = build_resolv_conf(nameservers, None);
    let path = std::path::Path::new(rootfs).join("etc/resolv.conf");
    if let Ok(meta) = std::fs::symlink_metadata(&path) {
        if meta.file_type().is_symlink() || meta.is_file() {
            let _ = std::fs::remove_file(&path);
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir resolv parent: {e}"))?;
    }
    std::fs::write(&path, &body).map_err(|e| format!("write resolv.conf: {e}"))?;
    Ok(body)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn posix_tz_matches_proot_kernel() {
        assert_eq!(posix_tz_from_offset("+0800").unwrap(), "LCL-8");
        assert_eq!(posix_tz_from_offset("+0530").unwrap(), "LCL-5:30");
        assert_eq!(posix_tz_from_offset("-0300").unwrap(), "LCL+3");
        assert_eq!(posix_tz_from_offset("+0000").unwrap(), "LCL-0");
        assert!(posix_tz_from_offset("GMT").is_none());
    }

    #[test]
    fn resolv_fallback_and_filter_loopback() {
        let parsed = parse_nameservers_from_resolv("nameserver 127.0.0.1\nnameserver 1.1.1.1\n");
        assert_eq!(parsed, vec!["1.1.1.1".to_string()]);
        let body = build_resolv_conf(&[], None);
        assert!(body.contains("8.8.8.8"));
        assert!(body.contains("8.8.4.4"));
    }

    #[test]
    fn dumpsys_dns_extract() {
        let sample = "    DnsAddresses: [ /192.168.1.1 , /2001:4860:4860::8888 ]\n";
        let got = parse_dumpsys_dns(sample);
        assert!(got.contains(&"192.168.1.1".into()));
    }

    #[test]
    fn proxy_six_keys_always_present() {
        let empty = proxy_block("");
        assert_eq!(empty.len(), 8);
        assert_eq!(empty["HTTP_PROXY"], "");
        let set = proxy_block("http://127.0.0.1:8080");
        assert_eq!(set["https_proxy"], "http://127.0.0.1:8080");
        assert_eq!(set["NO_PROXY"], PROXY_NO_PROXY);
    }

    #[test]
    fn guest_env_has_tool_compat_and_no_uv_link_mode() {
        let env = guest_env("LCL-8", "", "/workspace", &BTreeMap::new());
        assert_eq!(env["NO_COLOR"], "1");
        assert_eq!(env["PYTHONDONTWRITEBYTECODE"], "1");
        assert_eq!(env["GOMAXPROCS"], "2");
        assert_eq!(env["TZ"], "LCL-8");
        assert!(!env.contains_key("UV_LINK_MODE"));
        assert!(env["PATH"].contains("/usr/bin"));
    }

    #[test]
    fn guest_env_drops_dangerous_dynamic_linker_keys() {
        let mut extra = BTreeMap::new();
        extra.insert("LD_PRELOAD".into(), "/evil.so".into());
        extra.insert("LD_LIBRARY_PATH".into(), "/evil/lib".into());
        extra.insert("FOO".into(), "bar".into());
        let env = guest_env("LCL-8", "", "/workspace", &extra);
        assert!(!env.contains_key("LD_PRELOAD"));
        assert!(!env.contains_key("LD_LIBRARY_PATH"));
        assert_eq!(env["FOO"], "bar");
    }
}
